/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System.Runtime.Serialization;
using Newtonsoft.Json.Converters;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Defines CallsTranscriptionLanguage.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.Text.Json.Serialization.JsonConverter(typeof(JsonStringEnumMemberConverter<CallsTranscriptionLanguage>))]
    public enum CallsTranscriptionLanguage
    {
        /// <summary>
        ///     Enum AfZA for value: af-ZA
        /// </summary>
        [EnumMember(Value = "af-ZA")] AfZA = 1,

        /// <summary>
        ///     Enum SqAL for value: sq-AL
        /// </summary>
        [EnumMember(Value = "sq-AL")] SqAL = 2,

        /// <summary>
        ///     Enum AmET for value: am-ET
        /// </summary>
        [EnumMember(Value = "am-ET")] AmET = 3,

        /// <summary>
        ///     Enum ArKW for value: ar-KW
        /// </summary>
        [EnumMember(Value = "ar-KW")] ArKW = 4,

        /// <summary>
        ///     Enum ArAE for value: ar-AE
        /// </summary>
        [EnumMember(Value = "ar-AE")] ArAE = 5,

        /// <summary>
        ///     Enum ArBH for value: ar-BH
        /// </summary>
        [EnumMember(Value = "ar-BH")] ArBH = 6,

        /// <summary>
        ///     Enum ArDZ for value: ar-DZ
        /// </summary>
        [EnumMember(Value = "ar-DZ")] ArDZ = 7,

        /// <summary>
        ///     Enum ArEG for value: ar-EG
        /// </summary>
        [EnumMember(Value = "ar-EG")] ArEG = 8,

        /// <summary>
        ///     Enum ArIL for value: ar-IL
        /// </summary>
        [EnumMember(Value = "ar-IL")] ArIL = 9,

        /// <summary>
        ///     Enum ArIQ for value: ar-IQ
        /// </summary>
        [EnumMember(Value = "ar-IQ")] ArIQ = 10,

        /// <summary>
        ///     Enum ArJO for value: ar-JO
        /// </summary>
        [EnumMember(Value = "ar-JO")] ArJO = 11,

        /// <summary>
        ///     Enum ArLB for value: ar-LB
        /// </summary>
        [EnumMember(Value = "ar-LB")] ArLB = 12,

        /// <summary>
        ///     Enum ArLY for value: ar-LY
        /// </summary>
        [EnumMember(Value = "ar-LY")] ArLY = 13,

        /// <summary>
        ///     Enum ArMA for value: ar-MA
        /// </summary>
        [EnumMember(Value = "ar-MA")] ArMA = 14,

        /// <summary>
        ///     Enum ArOM for value: ar-OM
        /// </summary>
        [EnumMember(Value = "ar-OM")] ArOM = 15,

        /// <summary>
        ///     Enum ArPS for value: ar-PS
        /// </summary>
        [EnumMember(Value = "ar-PS")] ArPS = 16,

        /// <summary>
        ///     Enum ArQA for value: ar-QA
        /// </summary>
        [EnumMember(Value = "ar-QA")] ArQA = 17,

        /// <summary>
        ///     Enum ArSA for value: ar-SA
        /// </summary>
        [EnumMember(Value = "ar-SA")] ArSA = 18,

        /// <summary>
        ///     Enum ArSY for value: ar-SY
        /// </summary>
        [EnumMember(Value = "ar-SY")] ArSY = 19,

        /// <summary>
        ///     Enum ArTN for value: ar-TN
        /// </summary>
        [EnumMember(Value = "ar-TN")] ArTN = 20,

        /// <summary>
        ///     Enum ArYE for value: ar-YE
        /// </summary>
        [EnumMember(Value = "ar-YE")] ArYE = 21,

        /// <summary>
        ///     Enum HyAM for value: hy-AM
        /// </summary>
        [EnumMember(Value = "hy-AM")] HyAM = 22,

        /// <summary>
        ///     Enum AzAZ for value: az-AZ
        /// </summary>
        [EnumMember(Value = "az-AZ")] AzAZ = 23,

        /// <summary>
        ///     Enum EuES for value: eu-ES
        /// </summary>
        [EnumMember(Value = "eu-ES")] EuES = 24,

        /// <summary>
        ///     Enum BnIN for value: bn-IN
        /// </summary>
        [EnumMember(Value = "bn-IN")] BnIN = 25,

        /// <summary>
        ///     Enum BnBD for value: bn-BD
        /// </summary>
        [EnumMember(Value = "bn-BD")] BnBD = 26,

        /// <summary>
        ///     Enum BsBA for value: bs-BA
        /// </summary>
        [EnumMember(Value = "bs-BA")] BsBA = 27,

        /// <summary>
        ///     Enum BgBG for value: bg-BG
        /// </summary>
        [EnumMember(Value = "bg-BG")] BgBG = 28,

        /// <summary>
        ///     Enum MyMM for value: my-MM
        /// </summary>
        [EnumMember(Value = "my-MM")] MyMM = 29,

        /// <summary>
        ///     Enum CaES for value: ca-ES
        /// </summary>
        [EnumMember(Value = "ca-ES")] CaES = 30,

        /// <summary>
        ///     Enum ZhCN for value: zh-CN
        /// </summary>
        [EnumMember(Value = "zh-CN")] ZhCN = 31,

        /// <summary>
        ///     Enum ZhHK for value: zh-HK
        /// </summary>
        [EnumMember(Value = "zh-HK")] ZhHK = 32,

        /// <summary>
        ///     Enum ZhTW for value: zh-TW
        /// </summary>
        [EnumMember(Value = "zh-TW")] ZhTW = 33,

        /// <summary>
        ///     Enum HrHR for value: hr-HR
        /// </summary>
        [EnumMember(Value = "hr-HR")] HrHR = 34,

        /// <summary>
        ///     Enum CsCZ for value: cs-CZ
        /// </summary>
        [EnumMember(Value = "cs-CZ")] CsCZ = 35,

        /// <summary>
        ///     Enum DaDK for value: da-DK
        /// </summary>
        [EnumMember(Value = "da-DK")] DaDK = 36,

        /// <summary>
        ///     Enum NlNL for value: nl-NL
        /// </summary>
        [EnumMember(Value = "nl-NL")] NlNL = 37,

        /// <summary>
        ///     Enum NlBE for value: nl-BE
        /// </summary>
        [EnumMember(Value = "nl-BE")] NlBE = 38,

        /// <summary>
        ///     Enum EnAU for value: en-AU
        /// </summary>
        [EnumMember(Value = "en-AU")] EnAU = 39,

        /// <summary>
        ///     Enum EnCA for value: en-CA
        /// </summary>
        [EnumMember(Value = "en-CA")] EnCA = 40,

        /// <summary>
        ///     Enum EnGB for value: en-GB
        /// </summary>
        [EnumMember(Value = "en-GB")] EnGB = 41,

        /// <summary>
        ///     Enum EnGH for value: en-GH
        /// </summary>
        [EnumMember(Value = "en-GH")] EnGH = 42,

        /// <summary>
        ///     Enum EnHK for value: en-HK
        /// </summary>
        [EnumMember(Value = "en-HK")] EnHK = 43,

        /// <summary>
        ///     Enum EnIE for value: en-IE
        /// </summary>
        [EnumMember(Value = "en-IE")] EnIE = 44,

        /// <summary>
        ///     Enum EnIN for value: en-IN
        /// </summary>
        [EnumMember(Value = "en-IN")] EnIN = 45,

        /// <summary>
        ///     Enum EnKE for value: en-KE
        /// </summary>
        [EnumMember(Value = "en-KE")] EnKE = 46,

        /// <summary>
        ///     Enum EnNG for value: en-NG
        /// </summary>
        [EnumMember(Value = "en-NG")] EnNG = 47,

        /// <summary>
        ///     Enum EnNZ for value: en-NZ
        /// </summary>
        [EnumMember(Value = "en-NZ")] EnNZ = 48,

        /// <summary>
        ///     Enum EnPH for value: en-PH
        /// </summary>
        [EnumMember(Value = "en-PH")] EnPH = 49,

        /// <summary>
        ///     Enum EnPK for value: en-PK
        /// </summary>
        [EnumMember(Value = "en-PK")] EnPK = 50,

        /// <summary>
        ///     Enum EnSG for value: en-SG
        /// </summary>
        [EnumMember(Value = "en-SG")] EnSG = 51,

        /// <summary>
        ///     Enum EnTZ for value: en-TZ
        /// </summary>
        [EnumMember(Value = "en-TZ")] EnTZ = 52,

        /// <summary>
        ///     Enum EnUS for value: en-US
        /// </summary>
        [EnumMember(Value = "en-US")] EnUS = 53,

        /// <summary>
        ///     Enum EnZA for value: en-ZA
        /// </summary>
        [EnumMember(Value = "en-ZA")] EnZA = 54,

        /// <summary>
        ///     Enum EtEE for value: et-EE
        /// </summary>
        [EnumMember(Value = "et-EE")] EtEE = 55,

        /// <summary>
        ///     Enum FilPH for value: fil-PH
        /// </summary>
        [EnumMember(Value = "fil-PH")] FilPH = 56,

        /// <summary>
        ///     Enum FiFI for value: fi-FI
        /// </summary>
        [EnumMember(Value = "fi-FI")] FiFI = 57,

        /// <summary>
        ///     Enum FrBE for value: fr-BE
        /// </summary>
        [EnumMember(Value = "fr-BE")] FrBE = 58,

        /// <summary>
        ///     Enum FrCA for value: fr-CA
        /// </summary>
        [EnumMember(Value = "fr-CA")] FrCA = 59,

        /// <summary>
        ///     Enum FrCH for value: fr-CH
        /// </summary>
        [EnumMember(Value = "fr-CH")] FrCH = 60,

        /// <summary>
        ///     Enum FrFR for value: fr-FR
        /// </summary>
        [EnumMember(Value = "fr-FR")] FrFR = 61,

        /// <summary>
        ///     Enum GlES for value: gl-ES
        /// </summary>
        [EnumMember(Value = "gl-ES")] GlES = 62,

        /// <summary>
        ///     Enum KaGE for value: ka-GE
        /// </summary>
        [EnumMember(Value = "ka-GE")] KaGE = 63,

        /// <summary>
        ///     Enum DeAT for value: de-AT
        /// </summary>
        [EnumMember(Value = "de-AT")] DeAT = 64,

        /// <summary>
        ///     Enum DeCH for value: de-CH
        /// </summary>
        [EnumMember(Value = "de-CH")] DeCH = 65,

        /// <summary>
        ///     Enum DeDE for value: de-DE
        /// </summary>
        [EnumMember(Value = "de-DE")] DeDE = 66,

        /// <summary>
        ///     Enum ElGR for value: el-GR
        /// </summary>
        [EnumMember(Value = "el-GR")] ElGR = 67,

        /// <summary>
        ///     Enum GuIN for value: gu-IN
        /// </summary>
        [EnumMember(Value = "gu-IN")] GuIN = 68,

        /// <summary>
        ///     Enum HeIL for value: he-IL
        /// </summary>
        [EnumMember(Value = "he-IL")] HeIL = 69,

        /// <summary>
        ///     Enum HiIN for value: hi-IN
        /// </summary>
        [EnumMember(Value = "hi-IN")] HiIN = 70,

        /// <summary>
        ///     Enum HuHU for value: hu-HU
        /// </summary>
        [EnumMember(Value = "hu-HU")] HuHU = 71,

        /// <summary>
        ///     Enum IsIS for value: is-IS
        /// </summary>
        [EnumMember(Value = "is-IS")] IsIS = 72,

        /// <summary>
        ///     Enum IdID for value: id-ID
        /// </summary>
        [EnumMember(Value = "id-ID")] IdID = 73,

        /// <summary>
        ///     Enum GaIE for value: ga-IE
        /// </summary>
        [EnumMember(Value = "ga-IE")] GaIE = 74,

        /// <summary>
        ///     Enum ItCH for value: it-CH
        /// </summary>
        [EnumMember(Value = "it-CH")] ItCH = 75,

        /// <summary>
        ///     Enum ItIT for value: it-IT
        /// </summary>
        [EnumMember(Value = "it-IT")] ItIT = 76,

        /// <summary>
        ///     Enum JaJP for value: ja-JP
        /// </summary>
        [EnumMember(Value = "ja-JP")] JaJP = 77,

        /// <summary>
        ///     Enum JvID for value: jv-ID
        /// </summary>
        [EnumMember(Value = "jv-ID")] JvID = 78,

        /// <summary>
        ///     Enum KnIN for value: kn-IN
        /// </summary>
        [EnumMember(Value = "kn-IN")] KnIN = 79,

        /// <summary>
        ///     Enum KkKZ for value: kk-KZ
        /// </summary>
        [EnumMember(Value = "kk-KZ")] KkKZ = 80,

        /// <summary>
        ///     Enum KmKH for value: km-KH
        /// </summary>
        [EnumMember(Value = "km-KH")] KmKH = 81,

        /// <summary>
        ///     Enum KoKR for value: ko-KR
        /// </summary>
        [EnumMember(Value = "ko-KR")] KoKR = 82,

        /// <summary>
        ///     Enum LoLA for value: lo-LA
        /// </summary>
        [EnumMember(Value = "lo-LA")] LoLA = 83,

        /// <summary>
        ///     Enum LvLV for value: lv-LV
        /// </summary>
        [EnumMember(Value = "lv-LV")] LvLV = 84,

        /// <summary>
        ///     Enum LtLT for value: lt-LT
        /// </summary>
        [EnumMember(Value = "lt-LT")] LtLT = 85,

        /// <summary>
        ///     Enum MkMK for value: mk-MK
        /// </summary>
        [EnumMember(Value = "mk-MK")] MkMK = 86,

        /// <summary>
        ///     Enum MsMY for value: ms-MY
        /// </summary>
        [EnumMember(Value = "ms-MY")] MsMY = 87,

        /// <summary>
        ///     Enum MlIN for value: ml-IN
        /// </summary>
        [EnumMember(Value = "ml-IN")] MlIN = 88,

        /// <summary>
        ///     Enum MtMT for value: mt-MT
        /// </summary>
        [EnumMember(Value = "mt-MT")] MtMT = 89,

        /// <summary>
        ///     Enum MrIN for value: mr-IN
        /// </summary>
        [EnumMember(Value = "mr-IN")] MrIN = 90,

        /// <summary>
        ///     Enum MnMN for value: mn-MN
        /// </summary>
        [EnumMember(Value = "mn-MN")] MnMN = 91,

        /// <summary>
        ///     Enum NeNP for value: ne-NP
        /// </summary>
        [EnumMember(Value = "ne-NP")] NeNP = 92,

        /// <summary>
        ///     Enum NoNO for value: no-NO
        /// </summary>
        [EnumMember(Value = "no-NO")] NoNO = 93,

        /// <summary>
        ///     Enum FaIR for value: fa-IR
        /// </summary>
        [EnumMember(Value = "fa-IR")] FaIR = 94,

        /// <summary>
        ///     Enum PlPL for value: pl-PL
        /// </summary>
        [EnumMember(Value = "pl-PL")] PlPL = 95,

        /// <summary>
        ///     Enum PtPT for value: pt-PT
        /// </summary>
        [EnumMember(Value = "pt-PT")] PtPT = 96,

        /// <summary>
        ///     Enum PtBR for value: pt-BR
        /// </summary>
        [EnumMember(Value = "pt-BR")] PtBR = 97,

        /// <summary>
        ///     Enum PaGuruIN for value: pa-Guru-IN
        /// </summary>
        [EnumMember(Value = "pa-Guru-IN")] PaGuruIN = 98,

        /// <summary>
        ///     Enum RoRO for value: ro-RO
        /// </summary>
        [EnumMember(Value = "ro-RO")] RoRO = 99,

        /// <summary>
        ///     Enum RuRU for value: ru-RU
        /// </summary>
        [EnumMember(Value = "ru-RU")] RuRU = 100,

        /// <summary>
        ///     Enum SrRS for value: sr-RS
        /// </summary>
        [EnumMember(Value = "sr-RS")] SrRS = 101,

        /// <summary>
        ///     Enum SiLK for value: si-LK
        /// </summary>
        [EnumMember(Value = "si-LK")] SiLK = 102,

        /// <summary>
        ///     Enum SkSK for value: sk-SK
        /// </summary>
        [EnumMember(Value = "sk-SK")] SkSK = 103,

        /// <summary>
        ///     Enum SlSI for value: sl-SI
        /// </summary>
        [EnumMember(Value = "sl-SI")] SlSI = 104,

        /// <summary>
        ///     Enum EsBO for value: es-BO
        /// </summary>
        [EnumMember(Value = "es-BO")] EsBO = 105,

        /// <summary>
        ///     Enum EsAR for value: es-AR
        /// </summary>
        [EnumMember(Value = "es-AR")] EsAR = 106,

        /// <summary>
        ///     Enum EsCL for value: es-CL
        /// </summary>
        [EnumMember(Value = "es-CL")] EsCL = 107,

        /// <summary>
        ///     Enum EsCO for value: es-CO
        /// </summary>
        [EnumMember(Value = "es-CO")] EsCO = 108,

        /// <summary>
        ///     Enum EsCR for value: es-CR
        /// </summary>
        [EnumMember(Value = "es-CR")] EsCR = 109,

        /// <summary>
        ///     Enum EsCU for value: es-CU
        /// </summary>
        [EnumMember(Value = "es-CU")] EsCU = 110,

        /// <summary>
        ///     Enum EsDO for value: es-DO
        /// </summary>
        [EnumMember(Value = "es-DO")] EsDO = 111,

        /// <summary>
        ///     Enum EsEC for value: es-EC
        /// </summary>
        [EnumMember(Value = "es-EC")] EsEC = 112,

        /// <summary>
        ///     Enum EsES for value: es-ES
        /// </summary>
        [EnumMember(Value = "es-ES")] EsES = 113,

        /// <summary>
        ///     Enum EsGQ for value: es-GQ
        /// </summary>
        [EnumMember(Value = "es-GQ")] EsGQ = 114,

        /// <summary>
        ///     Enum EsGT for value: es-GT
        /// </summary>
        [EnumMember(Value = "es-GT")] EsGT = 115,

        /// <summary>
        ///     Enum EsHN for value: es-HN
        /// </summary>
        [EnumMember(Value = "es-HN")] EsHN = 116,

        /// <summary>
        ///     Enum EsMX for value: es-MX
        /// </summary>
        [EnumMember(Value = "es-MX")] EsMX = 117,

        /// <summary>
        ///     Enum EsNI for value: es-NI
        /// </summary>
        [EnumMember(Value = "es-NI")] EsNI = 118,

        /// <summary>
        ///     Enum EsPA for value: es-PA
        /// </summary>
        [EnumMember(Value = "es-PA")] EsPA = 119,

        /// <summary>
        ///     Enum EsPE for value: es-PE
        /// </summary>
        [EnumMember(Value = "es-PE")] EsPE = 120,

        /// <summary>
        ///     Enum EsPR for value: es-PR
        /// </summary>
        [EnumMember(Value = "es-PR")] EsPR = 121,

        /// <summary>
        ///     Enum EsPY for value: es-PY
        /// </summary>
        [EnumMember(Value = "es-PY")] EsPY = 122,

        /// <summary>
        ///     Enum EsSV for value: es-SV
        /// </summary>
        [EnumMember(Value = "es-SV")] EsSV = 123,

        /// <summary>
        ///     Enum EsUS for value: es-US
        /// </summary>
        [EnumMember(Value = "es-US")] EsUS = 124,

        /// <summary>
        ///     Enum EsUY for value: es-UY
        /// </summary>
        [EnumMember(Value = "es-UY")] EsUY = 125,

        /// <summary>
        ///     Enum EsVE for value: es-VE
        /// </summary>
        [EnumMember(Value = "es-VE")] EsVE = 126,

        /// <summary>
        ///     Enum SuID for value: su-ID
        /// </summary>
        [EnumMember(Value = "su-ID")] SuID = 127,

        /// <summary>
        ///     Enum SwTZ for value: sw-TZ
        /// </summary>
        [EnumMember(Value = "sw-TZ")] SwTZ = 128,

        /// <summary>
        ///     Enum SwKE for value: sw-KE
        /// </summary>
        [EnumMember(Value = "sw-KE")] SwKE = 129,

        /// <summary>
        ///     Enum SvSE for value: sv-SE
        /// </summary>
        [EnumMember(Value = "sv-SE")] SvSE = 130,

        /// <summary>
        ///     Enum TaIN for value: ta-IN
        /// </summary>
        [EnumMember(Value = "ta-IN")] TaIN = 131,

        /// <summary>
        ///     Enum TaLK for value: ta-LK
        /// </summary>
        [EnumMember(Value = "ta-LK")] TaLK = 132,

        /// <summary>
        ///     Enum TaMY for value: ta-MY
        /// </summary>
        [EnumMember(Value = "ta-MY")] TaMY = 133,

        /// <summary>
        ///     Enum TaSG for value: ta-SG
        /// </summary>
        [EnumMember(Value = "ta-SG")] TaSG = 134,

        /// <summary>
        ///     Enum TeIN for value: te-IN
        /// </summary>
        [EnumMember(Value = "te-IN")] TeIN = 135,

        /// <summary>
        ///     Enum ThTH for value: th-TH
        /// </summary>
        [EnumMember(Value = "th-TH")] ThTH = 136,

        /// <summary>
        ///     Enum TrTR for value: tr-TR
        /// </summary>
        [EnumMember(Value = "tr-TR")] TrTR = 137,

        /// <summary>
        ///     Enum UkUA for value: uk-UA
        /// </summary>
        [EnumMember(Value = "uk-UA")] UkUA = 138,

        /// <summary>
        ///     Enum UrIN for value: ur-IN
        /// </summary>
        [EnumMember(Value = "ur-IN")] UrIN = 139,

        /// <summary>
        ///     Enum UrPK for value: ur-PK
        /// </summary>
        [EnumMember(Value = "ur-PK")] UrPK = 140,

        /// <summary>
        ///     Enum UzUZ for value: uz-UZ
        /// </summary>
        [EnumMember(Value = "uz-UZ")] UzUZ = 141,

        /// <summary>
        ///     Enum ViVN for value: vi-VN
        /// </summary>
        [EnumMember(Value = "vi-VN")] ViVN = 142,

        /// <summary>
        ///     Enum ZuZA for value: zu-ZA
        /// </summary>
        [EnumMember(Value = "zu-ZA")] ZuZA = 143
    }
}