/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System.Runtime.Serialization;
using Newtonsoft.Json.Converters;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     ID of an Infobip application to which the call is to be transferred..
    /// </summary>
    /// <value>ID of an Infobip application to which the call is to be transferred.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.Text.Json.Serialization.JsonConverter(
        typeof(JsonStringEnumMemberConverter<CallRoutingInfobipApplicationId>))]
    public enum CallRoutingInfobipApplicationId
    {
        /// <summary>
        ///     Enum Conversations for value: CONVERSATIONS
        /// </summary>
        [EnumMember(Value = "CONVERSATIONS")] Conversations = 1
    }
}