/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     CallsUpdateRequest
    /// </summary>
    [DataContract(Name = "CallsUpdateRequest")]
    [JsonObject]
    public class CallsUpdateRequest : IEquatable<CallsUpdateRequest>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="CallsUpdateRequest" /> class.
        /// </summary>
        /// <param name="muted">Indicates whether to mute or unmute the end user. This action prevents the user from talking..</param>
        /// <param name="deaf">
        ///     Indicates whether to deaf or undeaf the end user. This action prevents the user from hearing the
        ///     call..
        /// </param>
        /// <param name="blind">
        ///     Indicates whether to blind or unblind the end user. This action prevents the user from seeing any
        ///     remote video in the call. Only applicable for WebRTC endpoints..
        /// </param>
        /// <param name="role">role.</param>
        public CallsUpdateRequest(bool muted = default, bool deaf = default, bool blind = default,
            CallsRole role = default)
        {
            Muted = muted;
            Deaf = deaf;
            Blind = blind;
            Role = role;
        }

        /// <summary>
        ///     Indicates whether to mute or unmute the end user. This action prevents the user from talking.
        /// </summary>
        /// <value>Indicates whether to mute or unmute the end user. This action prevents the user from talking.</value>
        [DataMember(Name = "muted", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "muted", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("muted")]
        public bool Muted { get; set; }

        /// <summary>
        ///     Indicates whether to deaf or undeaf the end user. This action prevents the user from hearing the call.
        /// </summary>
        /// <value>Indicates whether to deaf or undeaf the end user. This action prevents the user from hearing the call.</value>
        [DataMember(Name = "deaf", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "deaf", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("deaf")]
        public bool Deaf { get; set; }

        /// <summary>
        ///     Indicates whether to blind or unblind the end user. This action prevents the user from seeing any remote video in
        ///     the call. Only applicable for WebRTC endpoints.
        /// </summary>
        /// <value>
        ///     Indicates whether to blind or unblind the end user. This action prevents the user from seeing any remote video
        ///     in the call. Only applicable for WebRTC endpoints.
        /// </value>
        [DataMember(Name = "blind", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "blind", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("blind")]
        public bool Blind { get; set; }

        /// <summary>
        ///     Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "role", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("role")]
        public CallsRole Role { get; set; }

        /// <summary>
        ///     Returns true if CallsUpdateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CallsUpdateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CallsUpdateRequest input)
        {
            if (input == null)
                return false;

            return
                (
                    Muted == input.Muted ||
                    Muted.Equals(input.Muted)
                ) &&
                (
                    Deaf == input.Deaf ||
                    Deaf.Equals(input.Deaf)
                ) &&
                (
                    Blind == input.Blind ||
                    Blind.Equals(input.Blind)
                ) &&
                (
                    Role == input.Role ||
                    (Role != null &&
                     Role.Equals(input.Role))
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CallsUpdateRequest {\n");
            sb.Append("  Muted: ").Append(Muted).Append("\n");
            sb.Append("  Deaf: ").Append(Deaf).Append("\n");
            sb.Append("  Blind: ").Append(Blind).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as CallsUpdateRequest);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                hashCode = hashCode * 59 + Muted.GetHashCode();
                hashCode = hashCode * 59 + Deaf.GetHashCode();
                hashCode = hashCode * 59 + Blind.GetHashCode();
                if (Role != null)
                    hashCode = hashCode * 59 + Role.GetHashCode();
                return hashCode;
            }
        }
    }
}