/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     CallsSearchResponse
    /// </summary>
    [DataContract(Name = "CallsSearchResponse")]
    [JsonObject]
    public class CallsSearchResponse : IEquatable<CallsSearchResponse>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="CallsSearchResponse" /> class.
        /// </summary>
        /// <param name="createTime">Creation timestamp..</param>
        /// <param name="description">Scenario description..</param>
        /// <param name="id">Scenario key. It is used for launching IVR scenario..</param>
        /// <param name="name">Scenario name..</param>
        /// <param name="notifyUrl">The URL on the client&#39;s callback server on which the Delivery report will be sent..</param>
        /// <param name="notifyContentType">
        ///     Preferred Delivery report content type. Can be &#x60;application/json&#x60; or &#x60;
        ///     application/xml&#x60;..
        /// </param>
        /// <param name="record">Indicates if all calls using the scenario should be recorded..</param>
        /// <param name="script">script.</param>
        /// <param name="updateTime">Update timestamp.</param>
        /// <param name="lastUsageDate">
        ///     Last usage date. &#x60;null&#x60; for scenarios that are used last time before &#x60;
        ///     2024-01-01&#x60;..
        /// </param>
        public CallsSearchResponse(DateTimeOffset createTime = default, string description = default,
            string id = default, string name = default, string notifyUrl = default, string notifyContentType = default,
            bool record = default, JRaw script = default, DateTimeOffset updateTime = default,
            DateTimeOffset lastUsageDate = default)
        {
            CreateTime = createTime;
            Description = description;
            Id = id;
            Name = name;
            NotifyUrl = notifyUrl;
            NotifyContentType = notifyContentType;
            Record = record;
            Script = script;
            UpdateTime = updateTime;
            LastUsageDate = lastUsageDate;
        }

        /// <summary>
        ///     Creation timestamp.
        /// </summary>
        /// <value>Creation timestamp.</value>
        [DataMember(Name = "createTime", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "createTime", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("createTime")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateTimeOffsetConverter))]
        public DateTimeOffset CreateTime { get; set; }

        /// <summary>
        ///     Scenario description.
        /// </summary>
        /// <value>Scenario description.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "description", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        ///     Scenario key. It is used for launching IVR scenario.
        /// </summary>
        /// <value>Scenario key. It is used for launching IVR scenario.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "id", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        ///     Scenario name.
        /// </summary>
        /// <value>Scenario name.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "name", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        ///     The URL on the client&#39;s callback server on which the Delivery report will be sent.
        /// </summary>
        /// <value>The URL on the client&#39;s callback server on which the Delivery report will be sent.</value>
        [DataMember(Name = "notifyUrl", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "notifyUrl", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("notifyUrl")]
        public string NotifyUrl { get; set; }

        /// <summary>
        ///     Preferred Delivery report content type. Can be &#x60;application/json&#x60; or &#x60;application/xml&#x60;.
        /// </summary>
        /// <value>Preferred Delivery report content type. Can be &#x60;application/json&#x60; or &#x60;application/xml&#x60;.</value>
        [DataMember(Name = "notifyContentType", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "notifyContentType", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("notifyContentType")]
        public string NotifyContentType { get; set; }

        /// <summary>
        ///     Indicates if all calls using the scenario should be recorded.
        /// </summary>
        /// <value>Indicates if all calls using the scenario should be recorded.</value>
        [DataMember(Name = "record", EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "record", DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("record")]
        public bool Record { get; set; }

        /// <summary>
        ///     Gets or Sets Script
        /// </summary>
        [DataMember(Name = "script", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "script", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("script")]
        public JRaw Script { get; set; }

        /// <summary>
        ///     Update timestamp
        /// </summary>
        /// <value>Update timestamp</value>
        [DataMember(Name = "updateTime", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "updateTime", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("updateTime")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateTimeOffsetConverter))]
        public DateTimeOffset UpdateTime { get; set; }

        /// <summary>
        ///     Last usage date. &#x60;null&#x60; for scenarios that are used last time before &#x60;2024-01-01&#x60;.
        /// </summary>
        /// <value>Last usage date. &#x60;null&#x60; for scenarios that are used last time before &#x60;2024-01-01&#x60;.</value>
        [DataMember(Name = "lastUsageDate", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "lastUsageDate", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("lastUsageDate")]
        public DateTimeOffset LastUsageDate { get; set; }

        /// <summary>
        ///     Returns true if CallsSearchResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CallsSearchResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CallsSearchResponse input)
        {
            if (input == null)
                return false;

            return
                (
                    CreateTime == input.CreateTime ||
                    (CreateTime != null &&
                     CreateTime.Equals(input.CreateTime))
                ) &&
                (
                    Description == input.Description ||
                    (Description != null &&
                     Description.Equals(input.Description))
                ) &&
                (
                    Id == input.Id ||
                    (Id != null &&
                     Id.Equals(input.Id))
                ) &&
                (
                    Name == input.Name ||
                    (Name != null &&
                     Name.Equals(input.Name))
                ) &&
                (
                    NotifyUrl == input.NotifyUrl ||
                    (NotifyUrl != null &&
                     NotifyUrl.Equals(input.NotifyUrl))
                ) &&
                (
                    NotifyContentType == input.NotifyContentType ||
                    (NotifyContentType != null &&
                     NotifyContentType.Equals(input.NotifyContentType))
                ) &&
                (
                    Record == input.Record ||
                    Record.Equals(input.Record)
                ) &&
                (
                    Script == input.Script ||
                    (Script != null &&
                     Script.Equals(input.Script))
                ) &&
                (
                    UpdateTime == input.UpdateTime ||
                    (UpdateTime != null &&
                     UpdateTime.Equals(input.UpdateTime))
                ) &&
                (
                    LastUsageDate == input.LastUsageDate ||
                    (LastUsageDate != null &&
                     LastUsageDate.Equals(input.LastUsageDate))
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CallsSearchResponse {\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NotifyUrl: ").Append(NotifyUrl).Append("\n");
            sb.Append("  NotifyContentType: ").Append(NotifyContentType).Append("\n");
            sb.Append("  Record: ").Append(Record).Append("\n");
            sb.Append("  Script: ").Append(Script).Append("\n");
            sb.Append("  UpdateTime: ").Append(UpdateTime).Append("\n");
            sb.Append("  LastUsageDate: ").Append(LastUsageDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as CallsSearchResponse);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (CreateTime != null)
                    hashCode = hashCode * 59 + CreateTime.GetHashCode();
                if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (NotifyUrl != null)
                    hashCode = hashCode * 59 + NotifyUrl.GetHashCode();
                if (NotifyContentType != null)
                    hashCode = hashCode * 59 + NotifyContentType.GetHashCode();
                hashCode = hashCode * 59 + Record.GetHashCode();
                if (Script != null)
                    hashCode = hashCode * 59 + Script.GetHashCode();
                if (UpdateTime != null)
                    hashCode = hashCode * 59 + UpdateTime.GetHashCode();
                if (LastUsageDate != null)
                    hashCode = hashCode * 59 + LastUsageDate.GetHashCode();
                return hashCode;
            }
        }
    }
}