/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     CallsDialogPropagationOptions
    /// </summary>
    [DataContract(Name = "CallsDialogPropagationOptions")]
    [JsonObject]
    public class CallsDialogPropagationOptions : IEquatable<CallsDialogPropagationOptions>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="CallsDialogPropagationOptions" /> class.
        /// </summary>
        /// <param name="childCallHangup">
        ///     Flag indicating if the parent call should be terminated when the child call ends.
        ///     (default to true).
        /// </param>
        /// <param name="childCallRinging">
        ///     Flag indicating if a child call&#39;s ringing should be propagated to the parent call.
        ///     The parent call must be &#x60;INBOUND&#x60;. Cannot be &#x60;true&#x60; when &#x60;ringbackGeneration&#x60; is
        ///     enabled. (default to false).
        /// </param>
        /// <param name="ringbackGeneration">ringbackGeneration.</param>
        public CallsDialogPropagationOptions(bool childCallHangup = true, bool childCallRinging = false,
            RingbackGeneration ringbackGeneration = default)
        {
            ChildCallHangup = childCallHangup;
            ChildCallRinging = childCallRinging;
            RingbackGeneration = ringbackGeneration;
        }

        /// <summary>
        ///     Flag indicating if the parent call should be terminated when the child call ends.
        /// </summary>
        /// <value>Flag indicating if the parent call should be terminated when the child call ends.</value>
        [DataMember(Name = "childCallHangup", EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "childCallHangup", DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("childCallHangup")]
        public bool ChildCallHangup { get; set; }

        /// <summary>
        ///     Flag indicating if a child call&#39;s ringing should be propagated to the parent call. The parent call must be
        ///     &#x60;INBOUND&#x60;. Cannot be &#x60;true&#x60; when &#x60;ringbackGeneration&#x60; is enabled.
        /// </summary>
        /// <value>
        ///     Flag indicating if a child call&#39;s ringing should be propagated to the parent call. The parent call must be
        ///     &#x60;INBOUND&#x60;. Cannot be &#x60;true&#x60; when &#x60;ringbackGeneration&#x60; is enabled.
        /// </value>
        [DataMember(Name = "childCallRinging", EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "childCallRinging", DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("childCallRinging")]
        public bool ChildCallRinging { get; set; }

        /// <summary>
        ///     Gets or Sets RingbackGeneration
        /// </summary>
        [DataMember(Name = "ringbackGeneration", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "ringbackGeneration", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("ringbackGeneration")]
        public RingbackGeneration RingbackGeneration { get; set; }

        /// <summary>
        ///     Returns true if CallsDialogPropagationOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of CallsDialogPropagationOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CallsDialogPropagationOptions input)
        {
            if (input == null)
                return false;

            return
                (
                    ChildCallHangup == input.ChildCallHangup ||
                    ChildCallHangup.Equals(input.ChildCallHangup)
                ) &&
                (
                    ChildCallRinging == input.ChildCallRinging ||
                    ChildCallRinging.Equals(input.ChildCallRinging)
                ) &&
                (
                    RingbackGeneration == input.RingbackGeneration ||
                    (RingbackGeneration != null &&
                     RingbackGeneration.Equals(input.RingbackGeneration))
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CallsDialogPropagationOptions {\n");
            sb.Append("  ChildCallHangup: ").Append(ChildCallHangup).Append("\n");
            sb.Append("  ChildCallRinging: ").Append(ChildCallRinging).Append("\n");
            sb.Append("  RingbackGeneration: ").Append(RingbackGeneration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as CallsDialogPropagationOptions);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                hashCode = hashCode * 59 + ChildCallHangup.GetHashCode();
                hashCode = hashCode * 59 + ChildCallRinging.GetHashCode();
                if (RingbackGeneration != null)
                    hashCode = hashCode * 59 + RingbackGeneration.GetHashCode();
                return hashCode;
            }
        }
    }
}