/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System.Runtime.Serialization;
using Newtonsoft.Json.Converters;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Indicates the risk status of email addresses. High-risk addresses have a very high chance of bouncing and
    ///     potentially damaging the sender&#39;s reputation. Low-risk addresses have a very low chance of bouncing and are
    ///     less likely to damage the sender&#39;s reputation. .
    /// </summary>
    /// <value>
    ///     Indicates the risk status of email addresses. High-risk addresses have a very high chance of bouncing and
    ///     potentially damaging the sender&#39;s reputation. Low-risk addresses have a very low chance of bouncing and are
    ///     less likely to damage the sender&#39;s reputation.
    /// </value>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.Text.Json.Serialization.JsonConverter(typeof(JsonStringEnumMemberConverter<EmailValidationApiRisk>))]
    public enum EmailValidationApiRisk
    {
        /// <summary>
        ///     Enum Low for value: LOW
        /// </summary>
        [EnumMember(Value = "LOW")] Low = 1,

        /// <summary>
        ///     Enum Medium for value: MEDIUM
        /// </summary>
        [EnumMember(Value = "MEDIUM")] Medium = 2,

        /// <summary>
        ///     Enum High for value: HIGH
        /// </summary>
        [EnumMember(Value = "HIGH")] High = 3,

        /// <summary>
        ///     Enum Unknown for value: UNKNOWN
        /// </summary>
        [EnumMember(Value = "UNKNOWN")] Unknown = 4
    }
}