/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Validation response
    /// </summary>
    [DataContract(Name = "EmailValidationResponse")]
    [JsonObject]
    public class EmailValidationResponse : IEquatable<EmailValidationResponse>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="EmailValidationResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EmailValidationResponse()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="EmailValidationResponse" /> class.
        /// </summary>
        /// <param name="to">The validated email address. (required).</param>
        /// <param name="validMailbox">Indicates whether email address is valid. (required).</param>
        /// <param name="validSyntax">Indicates whether email address syntax is valid. (required).</param>
        /// <param name="catchAll">Indicates catch all status of email address. (required).</param>
        /// <param name="didYouMean">Suggests similar alternate address that may be valid..</param>
        /// <param name="disposable">
        ///     Indicates whether email address is disposable. A disposable email address is a temporary
        ///     address that is often used for short-term purposes and can be discarded after use.  (required).
        /// </param>
        /// <param name="roleBased">
        ///     Indicates whether email address is role-based. A role-based email address is one that is
        ///     associated with a specific function or group within an organization, such as marketing@example.org, rather than an
        ///     individual person.  (required).
        /// </param>
        /// <param name="reason">reason.</param>
        /// <param name="risk">risk (required).</param>
        /// <param name="detailedReasons">
        ///     This field is provided when the validMailbox status is &#39;unknown&#39; or &#39;false
        ///     &#39;, offering specific explanations for why the email address has been assigned that status. .
        /// </param>
        public EmailValidationResponse(string to = default, string validMailbox = default, bool validSyntax = default,
            bool catchAll = default, string didYouMean = default, bool disposable = default, bool roleBased = default,
            EmailValidationReason? reason = default, EmailValidationApiRisk risk = default,
            string detailedReasons = default)
        {
            // to ensure "to" is required (not null)
            To = to ?? throw new ArgumentNullException("to");
            // to ensure "validMailbox" is required (not null)
            ValidMailbox = validMailbox ?? throw new ArgumentNullException("validMailbox");
            ValidSyntax = validSyntax;
            CatchAll = catchAll;
            Disposable = disposable;
            RoleBased = roleBased;
            Risk = risk;
            DidYouMean = didYouMean;
            Reason = reason;
            DetailedReasons = detailedReasons;
        }

        /// <summary>
        ///     Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "reason", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("reason")]
        public EmailValidationReason? Reason { get; set; }

        /// <summary>
        ///     Gets or Sets Risk
        /// </summary>
        [DataMember(Name = "risk", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "risk", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("risk")]
        public EmailValidationApiRisk Risk { get; set; }

        /// <summary>
        ///     The validated email address.
        /// </summary>
        /// <value>The validated email address.</value>
        [DataMember(Name = "to", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "to", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("to")]
        public string To { get; set; }

        /// <summary>
        ///     Indicates whether email address is valid.
        /// </summary>
        /// <value>Indicates whether email address is valid.</value>
        [DataMember(Name = "validMailbox", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "validMailbox", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("validMailbox")]
        public string ValidMailbox { get; set; }

        /// <summary>
        ///     Indicates whether email address syntax is valid.
        /// </summary>
        /// <value>Indicates whether email address syntax is valid.</value>
        [DataMember(Name = "validSyntax", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "validSyntax", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("validSyntax")]
        public bool ValidSyntax { get; set; }

        /// <summary>
        ///     Indicates catch all status of email address.
        /// </summary>
        /// <value>Indicates catch all status of email address.</value>
        [DataMember(Name = "catchAll", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "catchAll", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("catchAll")]
        public bool CatchAll { get; set; }

        /// <summary>
        ///     Suggests similar alternate address that may be valid.
        /// </summary>
        /// <value>Suggests similar alternate address that may be valid.</value>
        [DataMember(Name = "didYouMean", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "didYouMean", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("didYouMean")]
        public string DidYouMean { get; set; }

        /// <summary>
        ///     Indicates whether email address is disposable. A disposable email address is a temporary address that is often used
        ///     for short-term purposes and can be discarded after use.
        /// </summary>
        /// <value>
        ///     Indicates whether email address is disposable. A disposable email address is a temporary address that is often
        ///     used for short-term purposes and can be discarded after use.
        /// </value>
        [DataMember(Name = "disposable", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "disposable", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("disposable")]
        public bool Disposable { get; set; }

        /// <summary>
        ///     Indicates whether email address is role-based. A role-based email address is one that is associated with a specific
        ///     function or group within an organization, such as marketing@example.org, rather than an individual person.
        /// </summary>
        /// <value>
        ///     Indicates whether email address is role-based. A role-based email address is one that is associated with a
        ///     specific function or group within an organization, such as marketing@example.org, rather than an individual person.
        /// </value>
        [DataMember(Name = "roleBased", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "roleBased", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("roleBased")]
        public bool RoleBased { get; set; }

        /// <summary>
        ///     This field is provided when the validMailbox status is &#39;unknown&#39; or &#39;false&#39;, offering specific
        ///     explanations for why the email address has been assigned that status.
        /// </summary>
        /// <value>
        ///     This field is provided when the validMailbox status is &#39;unknown&#39; or &#39;false&#39;, offering specific
        ///     explanations for why the email address has been assigned that status.
        /// </value>
        [DataMember(Name = "detailedReasons", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "detailedReasons", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("detailedReasons")]
        public string DetailedReasons { get; set; }

        /// <summary>
        ///     Returns true if EmailValidationResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of EmailValidationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailValidationResponse input)
        {
            if (input == null)
                return false;

            return
                (
                    To == input.To ||
                    (To != null &&
                     To.Equals(input.To))
                ) &&
                (
                    ValidMailbox == input.ValidMailbox ||
                    (ValidMailbox != null &&
                     ValidMailbox.Equals(input.ValidMailbox))
                ) &&
                (
                    ValidSyntax == input.ValidSyntax ||
                    ValidSyntax.Equals(input.ValidSyntax)
                ) &&
                (
                    CatchAll == input.CatchAll ||
                    CatchAll.Equals(input.CatchAll)
                ) &&
                (
                    DidYouMean == input.DidYouMean ||
                    (DidYouMean != null &&
                     DidYouMean.Equals(input.DidYouMean))
                ) &&
                (
                    Disposable == input.Disposable ||
                    Disposable.Equals(input.Disposable)
                ) &&
                (
                    RoleBased == input.RoleBased ||
                    RoleBased.Equals(input.RoleBased)
                ) &&
                (
                    Reason == input.Reason ||
                    Reason.Equals(input.Reason)
                ) &&
                (
                    Risk == input.Risk ||
                    Risk.Equals(input.Risk)
                ) &&
                (
                    DetailedReasons == input.DetailedReasons ||
                    (DetailedReasons != null &&
                     DetailedReasons.Equals(input.DetailedReasons))
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailValidationResponse {\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  ValidMailbox: ").Append(ValidMailbox).Append("\n");
            sb.Append("  ValidSyntax: ").Append(ValidSyntax).Append("\n");
            sb.Append("  CatchAll: ").Append(CatchAll).Append("\n");
            sb.Append("  DidYouMean: ").Append(DidYouMean).Append("\n");
            sb.Append("  Disposable: ").Append(Disposable).Append("\n");
            sb.Append("  RoleBased: ").Append(RoleBased).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Risk: ").Append(Risk).Append("\n");
            sb.Append("  DetailedReasons: ").Append(DetailedReasons).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as EmailValidationResponse);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (To != null)
                    hashCode = hashCode * 59 + To.GetHashCode();
                if (ValidMailbox != null)
                    hashCode = hashCode * 59 + ValidMailbox.GetHashCode();
                hashCode = hashCode * 59 + ValidSyntax.GetHashCode();
                hashCode = hashCode * 59 + CatchAll.GetHashCode();
                if (DidYouMean != null)
                    hashCode = hashCode * 59 + DidYouMean.GetHashCode();
                hashCode = hashCode * 59 + Disposable.GetHashCode();
                hashCode = hashCode * 59 + RoleBased.GetHashCode();
                hashCode = hashCode * 59 + Reason.GetHashCode();
                hashCode = hashCode * 59 + Risk.GetHashCode();
                if (DetailedReasons != null)
                    hashCode = hashCode * 59 + DetailedReasons.GetHashCode();
                return hashCode;
            }
        }
    }
}