/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System.Runtime.Serialization;
using Newtonsoft.Json.Converters;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Recipient Type must be &#x60;TACIR&#x60; or &#x60;BIREYSEL&#x60;..
    /// </summary>
    /// <value>Recipient Type must be &#x60;TACIR&#x60; or &#x60;BIREYSEL&#x60;.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.Text.Json.Serialization.JsonConverter(typeof(JsonStringEnumMemberConverter<IysRecipientType>))]
    public enum IysRecipientType
    {
        /// <summary>
        ///     Enum Bireysel for value: BIREYSEL
        /// </summary>
        [EnumMember(Value = "BIREYSEL")] Bireysel = 1,

        /// <summary>
        ///     Enum Tacir for value: TACIR
        /// </summary>
        [EnumMember(Value = "TACIR")] Tacir = 2
    }
}