/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     MessagesApiMessageOpenUrlButton
    /// </summary>
    [DataContract(Name = "MessagesApiMessageOpenUrlButton")]
    [JsonObject]
    public class MessagesApiMessageOpenUrlButton : MessagesApiMessageButton, IEquatable<MessagesApiMessageOpenUrlButton>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageOpenUrlButton" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesApiMessageOpenUrlButton()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageOpenUrlButton" /> class.
        /// </summary>
        /// <param name="text">Text to be displayed on the button. (required).</param>
        /// <param name="url">URL to be opened when clicked on the button. (required).</param>
        /// <param name="postbackData">Custom data that will be sent to you when the user replies to the message..</param>
        /// <param name="openIn">openIn.</param>
        /// <param name="type">type (required) (default to MessagesApiMessageButtonType.OpenUrl).</param>
        public MessagesApiMessageOpenUrlButton(string text = default, string url = default,
            string postbackData = default, MessagesApiOpenUrlButtonOpenIn? openIn = default,
            MessagesApiMessageButtonType type = MessagesApiMessageButtonType.OpenUrl) : base(type)
        {
            // to ensure "text" is required (not null)
            Text = text ?? throw new ArgumentNullException("text");
            // to ensure "url" is required (not null)
            Url = url ?? throw new ArgumentNullException("url");
            PostbackData = postbackData;
            OpenIn = openIn;
        }

        /// <summary>
        ///     Gets or Sets OpenIn
        /// </summary>
        [DataMember(Name = "openIn", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "openIn", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("openIn")]
        public MessagesApiOpenUrlButtonOpenIn? OpenIn { get; set; }

        /// <summary>
        ///     Text to be displayed on the button.
        /// </summary>
        /// <value>Text to be displayed on the button.</value>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "text", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        ///     URL to be opened when clicked on the button.
        /// </summary>
        /// <value>URL to be opened when clicked on the button.</value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "url", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        ///     Custom data that will be sent to you when the user replies to the message.
        /// </summary>
        /// <value>Custom data that will be sent to you when the user replies to the message.</value>
        [DataMember(Name = "postbackData", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "postbackData", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("postbackData")]
        public string PostbackData { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiMessageOpenUrlButton instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiMessageOpenUrlButton to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiMessageOpenUrlButton input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                   (
                       Text == input.Text ||
                       (Text != null &&
                        Text.Equals(input.Text))
                   ) && base.Equals(input) &&
                   (
                       Url == input.Url ||
                       (Url != null &&
                        Url.Equals(input.Url))
                   ) && base.Equals(input) &&
                   (
                       PostbackData == input.PostbackData ||
                       (PostbackData != null &&
                        PostbackData.Equals(input.PostbackData))
                   ) && base.Equals(input) &&
                   (
                       OpenIn == input.OpenIn ||
                       OpenIn.Equals(input.OpenIn)
                   );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiMessageOpenUrlButton {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  PostbackData: ").Append(PostbackData).Append("\n");
            sb.Append("  OpenIn: ").Append(OpenIn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiMessageOpenUrlButton);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();
                if (Text != null)
                    hashCode = hashCode * 59 + Text.GetHashCode();
                if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                if (PostbackData != null)
                    hashCode = hashCode * 59 + PostbackData.GetHashCode();
                hashCode = hashCode * 59 + OpenIn.GetHashCode();
                return hashCode;
            }
        }
    }
}