/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System.Runtime.Serialization;
using Newtonsoft.Json.Converters;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Status of the order..
    /// </summary>
    /// <value>Status of the order.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.Text.Json.Serialization.JsonConverter(
        typeof(JsonStringEnumMemberConverter<MessagesApiMessageOrderStatusOrderStatus>))]
    public enum MessagesApiMessageOrderStatusOrderStatus
    {
        /// <summary>
        ///     Enum Pending for value: PENDING
        /// </summary>
        [EnumMember(Value = "PENDING")] Pending = 1,

        /// <summary>
        ///     Enum Processing for value: PROCESSING
        /// </summary>
        [EnumMember(Value = "PROCESSING")] Processing = 2,

        /// <summary>
        ///     Enum PartiallyShipped for value: PARTIALLY_SHIPPED
        /// </summary>
        [EnumMember(Value = "PARTIALLY_SHIPPED")]
        PartiallyShipped = 3,

        /// <summary>
        ///     Enum Shipped for value: SHIPPED
        /// </summary>
        [EnumMember(Value = "SHIPPED")] Shipped = 4,

        /// <summary>
        ///     Enum Completed for value: COMPLETED
        /// </summary>
        [EnumMember(Value = "COMPLETED")] Completed = 5,

        /// <summary>
        ///     Enum Canceled for value: CANCELED
        /// </summary>
        [EnumMember(Value = "CANCELED")] Canceled = 6
    }
}