/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System.Runtime.Serialization;
using Newtonsoft.Json.Converters;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Defines MessagesApiMessageBodyType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.Text.Json.Serialization.JsonConverter(typeof(JsonStringEnumMemberConverter<MessagesApiMessageBodyType>))]
    public enum MessagesApiMessageBodyType
    {
        /// <summary>
        ///     Enum Text for value: TEXT
        /// </summary>
        [EnumMember(Value = "TEXT")] Text = 1,

        /// <summary>
        ///     Enum Image for value: IMAGE
        /// </summary>
        [EnumMember(Value = "IMAGE")] Image = 2,

        /// <summary>
        ///     Enum Video for value: VIDEO
        /// </summary>
        [EnumMember(Value = "VIDEO")] Video = 3,

        /// <summary>
        ///     Enum Document for value: DOCUMENT
        /// </summary>
        [EnumMember(Value = "DOCUMENT")] Document = 4,

        /// <summary>
        ///     Enum RichLink for value: RICH_LINK
        /// </summary>
        [EnumMember(Value = "RICH_LINK")] RichLink = 5,

        /// <summary>
        ///     Enum AuthenticationRequest for value: AUTHENTICATION_REQUEST
        /// </summary>
        [EnumMember(Value = "AUTHENTICATION_REQUEST")]
        AuthenticationRequest = 6,

        /// <summary>
        ///     Enum List for value: LIST
        /// </summary>
        [EnumMember(Value = "LIST")] List = 7,

        /// <summary>
        ///     Enum Carousel for value: CAROUSEL
        /// </summary>
        [EnumMember(Value = "CAROUSEL")] Carousel = 8,

        /// <summary>
        ///     Enum Location for value: LOCATION
        /// </summary>
        [EnumMember(Value = "LOCATION")] Location = 9,

        /// <summary>
        ///     Enum Contact for value: CONTACT
        /// </summary>
        [EnumMember(Value = "CONTACT")] Contact = 10,

        /// <summary>
        ///     Enum Sticker for value: STICKER
        /// </summary>
        [EnumMember(Value = "STICKER")] Sticker = 11,

        /// <summary>
        ///     Enum Product for value: PRODUCT
        /// </summary>
        [EnumMember(Value = "PRODUCT")] Product = 12,

        /// <summary>
        ///     Enum Mixed for value: MIXED
        /// </summary>
        [EnumMember(Value = "MIXED")] Mixed = 13,

        /// <summary>
        ///     Enum Flow for value: FLOW
        /// </summary>
        [EnumMember(Value = "FLOW")] Flow = 14,

        /// <summary>
        ///     Enum TimePicker for value: TIME_PICKER
        /// </summary>
        [EnumMember(Value = "TIME_PICKER")] TimePicker = 15,

        /// <summary>
        ///     Enum OrderRequest for value: ORDER_REQUEST
        /// </summary>
        [EnumMember(Value = "ORDER_REQUEST")] OrderRequest = 16,

        /// <summary>
        ///     Enum OrderStatus for value: ORDER_STATUS
        /// </summary>
        [EnumMember(Value = "ORDER_STATUS")] OrderStatus = 17,

        /// <summary>
        ///     Enum Form for value: FORM
        /// </summary>
        [EnumMember(Value = "FORM")] Form = 18
    }
}