/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Content of the message.
    /// </summary>
    [DataContract(Name = "MessagesApiTemplateMessageContent")]
    [JsonObject]
    public class MessagesApiTemplateMessageContent : IEquatable<MessagesApiTemplateMessageContent>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiTemplateMessageContent" /> class.
        /// </summary>
        /// <param name="header">header.</param>
        /// <param name="body">body.</param>
        /// <param name="buttons">List of buttons of a template message..</param>
        /// <param name="expirationTime">
        ///     Expiration time of a limited-time offer template message. Has the following format:
        ///     yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ..
        /// </param>
        public MessagesApiTemplateMessageContent(MessagesApiTemplateHeader header = default,
            MessagesApiTemplateBody body = default, List<MessagesApiTemplateButton> buttons = default,
            string expirationTime = default)
        {
            Header = header;
            Body = body;
            Buttons = buttons;
            ExpirationTime = expirationTime;
        }

        /// <summary>
        ///     Gets or Sets Header
        /// </summary>
        [DataMember(Name = "header", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "header", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("header")]
        public MessagesApiTemplateHeader Header { get; set; }

        /// <summary>
        ///     Gets or Sets Body
        /// </summary>
        [DataMember(Name = "body", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "body", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("body")]
        public MessagesApiTemplateBody Body { get; set; }

        /// <summary>
        ///     List of buttons of a template message.
        /// </summary>
        /// <value>List of buttons of a template message.</value>
        [DataMember(Name = "buttons", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "buttons", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("buttons")]
        public List<MessagesApiTemplateButton> Buttons { get; set; }

        /// <summary>
        ///     Expiration time of a limited-time offer template message. Has the following format: yyyy-MM-dd&#39;T&#39;
        ///     HH:mm:ss.SSSZ.
        /// </summary>
        /// <value>
        ///     Expiration time of a limited-time offer template message. Has the following format: yyyy-MM-dd&#39;T&#39;
        ///     HH:mm:ss.SSSZ.
        /// </value>
        [DataMember(Name = "expirationTime", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "expirationTime", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("expirationTime")]
        public string ExpirationTime { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiTemplateMessageContent instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiTemplateMessageContent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiTemplateMessageContent input)
        {
            if (input == null)
                return false;

            return
                (
                    Header == input.Header ||
                    (Header != null &&
                     Header.Equals(input.Header))
                ) &&
                (
                    Body == input.Body ||
                    (Body != null &&
                     Body.Equals(input.Body))
                ) &&
                (
                    Buttons == input.Buttons ||
                    (Buttons != null &&
                     input.Buttons != null &&
                     Buttons.SequenceEqual(input.Buttons))
                ) &&
                (
                    ExpirationTime == input.ExpirationTime ||
                    (ExpirationTime != null &&
                     ExpirationTime.Equals(input.ExpirationTime))
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiTemplateMessageContent {\n");
            sb.Append("  Header: ").Append(Header).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Buttons: ").Append(Buttons).Append("\n");
            sb.Append("  ExpirationTime: ").Append(ExpirationTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiTemplateMessageContent);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Header != null)
                    hashCode = hashCode * 59 + Header.GetHashCode();
                if (Body != null)
                    hashCode = hashCode * 59 + Body.GetHashCode();
                if (Buttons != null)
                    hashCode = hashCode * 59 + Buttons.GetHashCode();
                if (ExpirationTime != null)
                    hashCode = hashCode * 59 + ExpirationTime.GetHashCode();
                return hashCode;
            }
        }
    }
}