/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System.Runtime.Serialization;
using Newtonsoft.Json.Converters;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Orientation of the card..
    /// </summary>
    /// <value>Orientation of the card.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.Text.Json.Serialization.JsonConverter(
        typeof(JsonStringEnumMemberConverter<MessagesApiMessageCardOptionsOrientationEnum>))]
    public enum MessagesApiMessageCardOptionsOrientationEnum
    {
        /// <summary>
        ///     Enum Horizontal for value: HORIZONTAL
        /// </summary>
        [EnumMember(Value = "HORIZONTAL")] Horizontal = 1,

        /// <summary>
        ///     Enum Vertical for value: VERTICAL
        /// </summary>
        [EnumMember(Value = "VERTICAL")] Vertical = 2
    }
}