/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using JsonConverter = Newtonsoft.Json.JsonConverter;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Mixed items.
    /// </summary>
    [JsonConverter(typeof(MessagesApiMessageMixedItemJsonConverter))]
    [DataContract(Name = "MessagesApiMessageMixedItem")]
    [JsonObject]
    public class MessagesApiMessageMixedItem : AbstractOpenAPISchema, IEquatable<MessagesApiMessageMixedItem>,
        IValidatableObject
    {
        private object _actualInstance;

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageMixedItem" /> class
        ///     with the <see cref="MessagesApiMessageMixedMediaItem" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MessagesApiMessageMixedMediaItem.</param>
        public MessagesApiMessageMixedItem(MessagesApiMessageMixedMediaItem actualInstance)
        {
            IsNullable = false;
            SchemaType = "oneOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageMixedItem" /> class
        ///     with the <see cref="MessagesApiMessageMixedTextItem" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MessagesApiMessageMixedTextItem.</param>
        public MessagesApiMessageMixedItem(MessagesApiMessageMixedTextItem actualInstance)
        {
            IsNullable = false;
            SchemaType = "oneOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        ///     Gets or Sets ActualInstance
        /// </summary>
        public override object ActualInstance
        {
            get => _actualInstance;
            set
            {
                if (value.GetType() == typeof(MessagesApiMessageMixedMediaItem))
                    _actualInstance = value;
                else if (value.GetType() == typeof(MessagesApiMessageMixedTextItem))
                    _actualInstance = value;
                else
                    throw new ArgumentException(
                        "Invalid instance found. Must be the following types: MessagesApiMessageMixedMediaItem, MessagesApiMessageMixedTextItem");
            }
        }

        /// <summary>
        ///     Returns true if MessagesApiMessageMixedItem instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiMessageMixedItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiMessageMixedItem input)
        {
            if (input == null)
                return false;

            return ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Get the actual instance of `MessagesApiMessageMixedMediaItem`. If the actual instanct is not
        ///     `MessagesApiMessageMixedMediaItem`,
        ///     the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MessagesApiMessageMixedMediaItem</returns>
        public MessagesApiMessageMixedMediaItem GetMessagesApiMessageMixedMediaItem()
        {
            return (MessagesApiMessageMixedMediaItem)ActualInstance;
        }

        /// <summary>
        ///     Get the actual instance of `MessagesApiMessageMixedTextItem`. If the actual instanct is not
        ///     `MessagesApiMessageMixedTextItem`,
        ///     the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MessagesApiMessageMixedTextItem</returns>
        public MessagesApiMessageMixedTextItem GetMessagesApiMessageMixedTextItem()
        {
            return (MessagesApiMessageMixedTextItem)ActualInstance;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiMessageMixedItem {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, SerializerSettings);
        }

        /// <summary>
        ///     Converts the JSON string into an instance of MessagesApiMessageMixedItem
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of MessagesApiMessageMixedItem</returns>
        public static MessagesApiMessageMixedItem FromJson(string jsonString)
        {
            MessagesApiMessageMixedItem newMessagesApiMessageMixedItem = null;

            if (jsonString == null)
                return newMessagesApiMessageMixedItem;

            var match = 0;
            var matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MessagesApiMessageMixedMediaItem).GetProperty("AdditionalProperties") == null)
                    newMessagesApiMessageMixedItem = new MessagesApiMessageMixedItem(
                        JsonConvert.DeserializeObject<MessagesApiMessageMixedMediaItem>(jsonString,
                            SerializerSettings));

                else
                    newMessagesApiMessageMixedItem = new MessagesApiMessageMixedItem(
                        JsonConvert.DeserializeObject<MessagesApiMessageMixedMediaItem>(jsonString,
                            AdditionalPropertiesSerializerSettings));

                matchedTypes.Add("MessagesApiMessageMixedMediaItem");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                Debug.WriteLine("Failed to deserialize `{0}` into MessagesApiMessageMixedMediaItem: {1}", jsonString,
                    exception);
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MessagesApiMessageMixedTextItem).GetProperty("AdditionalProperties") == null)
                    newMessagesApiMessageMixedItem = new MessagesApiMessageMixedItem(
                        JsonConvert.DeserializeObject<MessagesApiMessageMixedTextItem>(jsonString, SerializerSettings));

                else
                    newMessagesApiMessageMixedItem = new MessagesApiMessageMixedItem(
                        JsonConvert.DeserializeObject<MessagesApiMessageMixedTextItem>(jsonString,
                            AdditionalPropertiesSerializerSettings));

                matchedTypes.Add("MessagesApiMessageMixedTextItem");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                Debug.WriteLine("Failed to deserialize `{0}` into MessagesApiMessageMixedTextItem: {1}", jsonString,
                    exception);
            }

            if (match == 0)
                throw new InvalidDataException("The JSON string `" + jsonString +
                                               "` cannot be deserialized into any schema defined.");

            if (match > 1)
                throw new InvalidDataException("The JSON string `" + jsonString +
                                               "` incorrectly matches more than one schema (should be exactly one match): " +
                                               matchedTypes);

            // deserialization is considered successful at this point if no exception has been thrown.
            return newMessagesApiMessageMixedItem;
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiMessageMixedItem);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (ActualInstance != null)
                    hashCode = hashCode * 59 + ActualInstance.GetHashCode();
                return hashCode;
            }
        }
    }

    /// <summary>
    ///     Custom JSON converter for MessagesApiMessageMixedItem
    /// </summary>
    public class MessagesApiMessageMixedItemJsonConverter : JsonConverter
    {
        /// <summary>
        ///     To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)typeof(MessagesApiMessageMixedItem).GetMethod("ToJson").Invoke(value, null));
        }

        /// <summary>
        ///     To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue,
            JsonSerializer serializer)
        {
            if (reader.TokenType != JsonToken.Null)
                return MessagesApiMessageMixedItem.FromJson(JObject.Load(reader).ToString(Formatting.None));
            return null;
        }

        /// <summary>
        ///     Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }
}