/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Provides options for configuring the delivery report behavior.
    /// </summary>
    [DataContract(Name = "MessagesApiDelivery")]
    [JsonObject]
    public class MessagesApiDelivery : IEquatable<MessagesApiDelivery>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiDelivery" /> class.
        /// </summary>
        /// <param name="url">
        ///     The URL on your call back server where a delivery report will be sent. If your URL becomes
        ///     unavailable then the [retry cycle](https://www.infobip.com/docs/sms/api#notify-url) uses the following formula:
        ///     &#x60;1min + (1min * retryNumber * retryNumber)&#x60;..
        /// </param>
        /// <param name="intermediateReport">
        ///     The real-time intermediate delivery report containing GSM error codes, messages
        ///     status, pricing, network and country codes, etc., which will be sent on your callback server. The default setting
        ///     is &#x60;false&#x60;..
        /// </param>
        /// <param name="receiveTriggeredFailoverReports">
        ///     Allows you to receive delivery reports for all triggered failover steps,
        ///     not just the final one (either the first successful or the last failed step). The default setting is &#x60;false
        ///     &#x60;..
        /// </param>
        public MessagesApiDelivery(string url = default, bool intermediateReport = default,
            bool receiveTriggeredFailoverReports = default)
        {
            Url = url;
            IntermediateReport = intermediateReport;
            ReceiveTriggeredFailoverReports = receiveTriggeredFailoverReports;
        }

        /// <summary>
        ///     The URL on your call back server where a delivery report will be sent. If your URL becomes unavailable then the
        ///     [retry cycle](https://www.infobip.com/docs/sms/api#notify-url) uses the following formula: &#x60;1min + (1min *
        ///     retryNumber * retryNumber)&#x60;.
        /// </summary>
        /// <value>
        ///     The URL on your call back server where a delivery report will be sent. If your URL becomes unavailable then the
        ///     [retry cycle](https://www.infobip.com/docs/sms/api#notify-url) uses the following formula: &#x60;1min + (1min *
        ///     retryNumber * retryNumber)&#x60;.
        /// </value>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "url", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        ///     The real-time intermediate delivery report containing GSM error codes, messages status, pricing, network and
        ///     country codes, etc., which will be sent on your callback server. The default setting is &#x60;false&#x60;.
        /// </summary>
        /// <value>
        ///     The real-time intermediate delivery report containing GSM error codes, messages status, pricing, network and
        ///     country codes, etc., which will be sent on your callback server. The default setting is &#x60;false&#x60;.
        /// </value>
        [DataMember(Name = "intermediateReport", EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "intermediateReport", DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("intermediateReport")]
        public bool IntermediateReport { get; set; }

        /// <summary>
        ///     Allows you to receive delivery reports for all triggered failover steps, not just the final one (either the first
        ///     successful or the last failed step). The default setting is &#x60;false&#x60;.
        /// </summary>
        /// <value>
        ///     Allows you to receive delivery reports for all triggered failover steps, not just the final one (either the
        ///     first successful or the last failed step). The default setting is &#x60;false&#x60;.
        /// </value>
        [DataMember(Name = "receiveTriggeredFailoverReports", EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "receiveTriggeredFailoverReports",
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("receiveTriggeredFailoverReports")]
        public bool ReceiveTriggeredFailoverReports { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiDelivery instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiDelivery to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiDelivery input)
        {
            if (input == null)
                return false;

            return
                (
                    Url == input.Url ||
                    (Url != null &&
                     Url.Equals(input.Url))
                ) &&
                (
                    IntermediateReport == input.IntermediateReport ||
                    IntermediateReport.Equals(input.IntermediateReport)
                ) &&
                (
                    ReceiveTriggeredFailoverReports == input.ReceiveTriggeredFailoverReports ||
                    ReceiveTriggeredFailoverReports.Equals(input.ReceiveTriggeredFailoverReports)
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiDelivery {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  IntermediateReport: ").Append(IntermediateReport).Append("\n");
            sb.Append("  ReceiveTriggeredFailoverReports: ").Append(ReceiveTriggeredFailoverReports).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiDelivery);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                hashCode = hashCode * 59 + IntermediateReport.GetHashCode();
                hashCode = hashCode * 59 + ReceiveTriggeredFailoverReports.GetHashCode();
                return hashCode;
            }
        }
    }
}