/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System.Runtime.Serialization;
using Newtonsoft.Json.Converters;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Messaging channel used for sending a message..
    /// </summary>
    /// <value>Messaging channel used for sending a message.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.Text.Json.Serialization.JsonConverter(
        typeof(JsonStringEnumMemberConverter<MessagesApiOutboundMessageChannel>))]
    public enum MessagesApiOutboundMessageChannel
    {
        /// <summary>
        ///     Enum AppleMb for value: APPLE_MB
        /// </summary>
        [EnumMember(Value = "APPLE_MB")] AppleMb = 1,

        /// <summary>
        ///     Enum InstagramDm for value: INSTAGRAM_DM
        /// </summary>
        [EnumMember(Value = "INSTAGRAM_DM")] InstagramDm = 2,

        /// <summary>
        ///     Enum LineOn for value: LINE_ON
        /// </summary>
        [EnumMember(Value = "LINE_ON")] LineOn = 3,

        /// <summary>
        ///     Enum Messenger for value: MESSENGER
        /// </summary>
        [EnumMember(Value = "MESSENGER")] Messenger = 4,

        /// <summary>
        ///     Enum Mms for value: MMS
        /// </summary>
        [EnumMember(Value = "MMS")] Mms = 5,

        /// <summary>
        ///     Enum Rcs for value: RCS
        /// </summary>
        [EnumMember(Value = "RCS")] Rcs = 6,

        /// <summary>
        ///     Enum Sms for value: SMS
        /// </summary>
        [EnumMember(Value = "SMS")] Sms = 7,

        /// <summary>
        ///     Enum ViberBm for value: VIBER_BM
        /// </summary>
        [EnumMember(Value = "VIBER_BM")] ViberBm = 8,

        /// <summary>
        ///     Enum ViberBot for value: VIBER_BOT
        /// </summary>
        [EnumMember(Value = "VIBER_BOT")] ViberBot = 9,

        /// <summary>
        ///     Enum Whatsapp for value: WHATSAPP
        /// </summary>
        [EnumMember(Value = "WHATSAPP")] Whatsapp = 10
    }
}