/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using JsonConverter = Newtonsoft.Json.JsonConverter;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Array of destination objects for where messages are being sent. A valid destination is required. **&#x60;Channels
    ///     Destination&#x60; is required when sending messages with defined failover.**
    /// </summary>
    [JsonConverter(typeof(MessagesApiMessageDestinationJsonConverter))]
    [DataContract(Name = "MessagesApiMessageDestination")]
    [JsonObject]
    public class MessagesApiMessageDestination : AbstractOpenAPISchema, IEquatable<MessagesApiMessageDestination>,
        IValidatableObject
    {
        private object _actualInstance;

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageDestination" /> class
        ///     with the <see cref="MessagesApiChannelsDestination" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MessagesApiChannelsDestination.</param>
        public MessagesApiMessageDestination(MessagesApiChannelsDestination actualInstance)
        {
            IsNullable = false;
            SchemaType = "oneOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageDestination" /> class
        ///     with the <see cref="MessagesApiToDestination" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MessagesApiToDestination.</param>
        public MessagesApiMessageDestination(MessagesApiToDestination actualInstance)
        {
            IsNullable = false;
            SchemaType = "oneOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        ///     Gets or Sets ActualInstance
        /// </summary>
        public override object ActualInstance
        {
            get => _actualInstance;
            set
            {
                if (value.GetType() == typeof(MessagesApiChannelsDestination))
                    _actualInstance = value;
                else if (value.GetType() == typeof(MessagesApiToDestination))
                    _actualInstance = value;
                else
                    throw new ArgumentException(
                        "Invalid instance found. Must be the following types: MessagesApiChannelsDestination, MessagesApiToDestination");
            }
        }

        /// <summary>
        ///     Returns true if MessagesApiMessageDestination instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiMessageDestination to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiMessageDestination input)
        {
            if (input == null)
                return false;

            return ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Get the actual instance of `MessagesApiChannelsDestination`. If the actual instanct is not
        ///     `MessagesApiChannelsDestination`,
        ///     the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MessagesApiChannelsDestination</returns>
        public MessagesApiChannelsDestination GetMessagesApiChannelsDestination()
        {
            return (MessagesApiChannelsDestination)ActualInstance;
        }

        /// <summary>
        ///     Get the actual instance of `MessagesApiToDestination`. If the actual instanct is not `MessagesApiToDestination`,
        ///     the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MessagesApiToDestination</returns>
        public MessagesApiToDestination GetMessagesApiToDestination()
        {
            return (MessagesApiToDestination)ActualInstance;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiMessageDestination {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, SerializerSettings);
        }

        /// <summary>
        ///     Converts the JSON string into an instance of MessagesApiMessageDestination
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of MessagesApiMessageDestination</returns>
        public static MessagesApiMessageDestination FromJson(string jsonString)
        {
            MessagesApiMessageDestination newMessagesApiMessageDestination = null;

            if (jsonString == null)
                return newMessagesApiMessageDestination;

            var match = 0;
            var matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MessagesApiChannelsDestination).GetProperty("AdditionalProperties") == null)
                    newMessagesApiMessageDestination = new MessagesApiMessageDestination(
                        JsonConvert.DeserializeObject<MessagesApiChannelsDestination>(jsonString, SerializerSettings));

                else
                    newMessagesApiMessageDestination = new MessagesApiMessageDestination(
                        JsonConvert.DeserializeObject<MessagesApiChannelsDestination>(jsonString,
                            AdditionalPropertiesSerializerSettings));

                matchedTypes.Add("MessagesApiChannelsDestination");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                Debug.WriteLine("Failed to deserialize `{0}` into MessagesApiChannelsDestination: {1}", jsonString,
                    exception);
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MessagesApiToDestination).GetProperty("AdditionalProperties") == null)
                    newMessagesApiMessageDestination = new MessagesApiMessageDestination(
                        JsonConvert.DeserializeObject<MessagesApiToDestination>(jsonString, SerializerSettings));

                else
                    newMessagesApiMessageDestination = new MessagesApiMessageDestination(
                        JsonConvert.DeserializeObject<MessagesApiToDestination>(jsonString,
                            AdditionalPropertiesSerializerSettings));

                matchedTypes.Add("MessagesApiToDestination");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                Debug.WriteLine("Failed to deserialize `{0}` into MessagesApiToDestination: {1}", jsonString,
                    exception);
            }

            if (match == 0)
                throw new InvalidDataException("The JSON string `" + jsonString +
                                               "` cannot be deserialized into any schema defined.");

            if (match > 1)
                throw new InvalidDataException("The JSON string `" + jsonString +
                                               "` incorrectly matches more than one schema (should be exactly one match): " +
                                               matchedTypes);

            // deserialization is considered successful at this point if no exception has been thrown.
            return newMessagesApiMessageDestination;
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiMessageDestination);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (ActualInstance != null)
                    hashCode = hashCode * 59 + ActualInstance.GetHashCode();
                return hashCode;
            }
        }
    }

    /// <summary>
    ///     Custom JSON converter for MessagesApiMessageDestination
    /// </summary>
    public class MessagesApiMessageDestinationJsonConverter : JsonConverter
    {
        /// <summary>
        ///     To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)typeof(MessagesApiMessageDestination).GetMethod("ToJson").Invoke(value, null));
        }

        /// <summary>
        ///     To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue,
            JsonSerializer serializer)
        {
            if (reader.TokenType != JsonToken.Null)
                return MessagesApiMessageDestination.FromJson(JObject.Load(reader).ToString(Formatting.None));
            return null;
        }

        /// <summary>
        ///     Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }
}