/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     MessagesApiTemplateVideoHeader
    /// </summary>
    [DataContract(Name = "MessagesApiTemplateVideoHeader")]
    [JsonObject]
    public class MessagesApiTemplateVideoHeader : MessagesApiTemplateHeader, IEquatable<MessagesApiTemplateVideoHeader>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiTemplateVideoHeader" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesApiTemplateVideoHeader()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiTemplateVideoHeader" /> class.
        /// </summary>
        /// <param name="url">URL of a video. (required).</param>
        /// <param name="type">type (required) (default to MessagesApiTemplateHeaderType.Video).</param>
        public MessagesApiTemplateVideoHeader(string url = default,
            MessagesApiTemplateHeaderType type = MessagesApiTemplateHeaderType.Video) : base(type)
        {
            // to ensure "url" is required (not null)
            Url = url ?? throw new ArgumentNullException("url");
        }

        /// <summary>
        ///     URL of a video.
        /// </summary>
        /// <value>URL of a video.</value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "url", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiTemplateVideoHeader instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiTemplateVideoHeader to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiTemplateVideoHeader input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                   (
                       Url == input.Url ||
                       (Url != null &&
                        Url.Equals(input.Url))
                   );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiTemplateVideoHeader {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiTemplateVideoHeader);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();
                if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                return hashCode;
            }
        }
    }
}