/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     MessagesApiMessageApplePayPaymentConfiguration
    /// </summary>
    [DataContract(Name = "MessagesApiMessageApplePayPaymentConfiguration")]
    [JsonObject]
    public class MessagesApiMessageApplePayPaymentConfiguration : MessagesApiMessagePaymentConfiguration,
        IEquatable<MessagesApiMessageApplePayPaymentConfiguration>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageApplePayPaymentConfiguration" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesApiMessageApplePayPaymentConfiguration()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageApplePayPaymentConfiguration" /> class.
        /// </summary>
        /// <param name="merchantDomain">The domain of the merchant&#39;s website..</param>
        /// <param name="merchantDisplayName">The merchant&#39;s display name..</param>
        /// <param name="merchantPaymentGatewayUrl">
        ///     The URL of the merchant&#39;s payment gateway. This is the URL that Apple Pay
        ///     uses to process payments..
        /// </param>
        /// <param name="merchantCountryCode">The two-letter ISO 3166 merchant’s country code..</param>
        /// <param name="currencyCode">The three-letter ISO 4217 currency code for the payment..</param>
        /// <param name="merchantCapabilities">
        ///     An array of payment capabilities supported by the merchant. The array must include
        ///     3DS..
        /// </param>
        /// <param name="supportedNetworks">
        ///     An array of payment networks supported by the merchant. The array must include one or
        ///     more of the following values: AMEX, DISCOVER, MASTERCARD, PRIVATE_LABEL or VISA..
        /// </param>
        /// <param name="requiredBillingFields">
        ///     The list of the customer&#39;s required billing information needed to process the
        ///     transaction..
        /// </param>
        /// <param name="requiredShippingFields">
        ///     The list of shipping or contact information required from the customer to fulfill
        ///     the order..
        /// </param>
        /// <param name="paymentMethodUpdateUrl">Called by Apple Pay when the user changes the payment method..</param>
        /// <param name="shippingContactUpdateUrl">Called by Apple Pay when the user changes their shipping address information..</param>
        /// <param name="shippingMethodUpdateUrl">Called by Apple Pay when the user changes the shipping method..</param>
        /// <param name="orderTrackingUrl">
        ///     Called by Apple Pay after completing the order provides you with an opportunity to
        ///     update the order information in your system..
        /// </param>
        /// <param name="fallbackUrl">
        ///     A URL that opens in a web browser so the user can complete the purchase if their device is
        ///     unable to make payments using Apple Pay..
        /// </param>
        /// <param name="type">type (required) (default to MessagesApiMessagePaymentConfigurationType.ApplePay).</param>
        public MessagesApiMessageApplePayPaymentConfiguration(string merchantDomain = default,
            string merchantDisplayName = default, string merchantPaymentGatewayUrl = default,
            string merchantCountryCode = default, string currencyCode = default,
            List<MessagesApiMessageApplePayPaymentConfigurationMerchantCapability> merchantCapabilities = default,
            List<MessagesApiMessageApplePayPaymentConfigurationNetwork> supportedNetworks = default,
            List<MessagesApiMessageApplePayPaymentConfigurationContactField> requiredBillingFields = default,
            List<MessagesApiMessageApplePayPaymentConfigurationContactField> requiredShippingFields = default,
            string paymentMethodUpdateUrl = default, string shippingContactUpdateUrl = default,
            string shippingMethodUpdateUrl = default, string orderTrackingUrl = default, string fallbackUrl = default,
            MessagesApiMessagePaymentConfigurationType type =
                MessagesApiMessagePaymentConfigurationType.ApplePay) : base(type)
        {
            MerchantDomain = merchantDomain;
            MerchantDisplayName = merchantDisplayName;
            MerchantPaymentGatewayUrl = merchantPaymentGatewayUrl;
            MerchantCountryCode = merchantCountryCode;
            CurrencyCode = currencyCode;
            MerchantCapabilities = merchantCapabilities;
            SupportedNetworks = supportedNetworks;
            RequiredBillingFields = requiredBillingFields;
            RequiredShippingFields = requiredShippingFields;
            PaymentMethodUpdateUrl = paymentMethodUpdateUrl;
            ShippingContactUpdateUrl = shippingContactUpdateUrl;
            ShippingMethodUpdateUrl = shippingMethodUpdateUrl;
            OrderTrackingUrl = orderTrackingUrl;
            FallbackUrl = fallbackUrl;
        }

        /// <summary>
        ///     The domain of the merchant&#39;s website.
        /// </summary>
        /// <value>The domain of the merchant&#39;s website.</value>
        [DataMember(Name = "merchantDomain", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "merchantDomain", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("merchantDomain")]
        public string MerchantDomain { get; set; }

        /// <summary>
        ///     The merchant&#39;s display name.
        /// </summary>
        /// <value>The merchant&#39;s display name.</value>
        [DataMember(Name = "merchantDisplayName", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "merchantDisplayName", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("merchantDisplayName")]
        public string MerchantDisplayName { get; set; }

        /// <summary>
        ///     The URL of the merchant&#39;s payment gateway. This is the URL that Apple Pay uses to process payments.
        /// </summary>
        /// <value>The URL of the merchant&#39;s payment gateway. This is the URL that Apple Pay uses to process payments.</value>
        [DataMember(Name = "merchantPaymentGatewayUrl", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "merchantPaymentGatewayUrl", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("merchantPaymentGatewayUrl")]
        public string MerchantPaymentGatewayUrl { get; set; }

        /// <summary>
        ///     The two-letter ISO 3166 merchant’s country code.
        /// </summary>
        /// <value>The two-letter ISO 3166 merchant’s country code.</value>
        [DataMember(Name = "merchantCountryCode", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "merchantCountryCode", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("merchantCountryCode")]
        public string MerchantCountryCode { get; set; }

        /// <summary>
        ///     The three-letter ISO 4217 currency code for the payment.
        /// </summary>
        /// <value>The three-letter ISO 4217 currency code for the payment.</value>
        [DataMember(Name = "currencyCode", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "currencyCode", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("currencyCode")]
        public string CurrencyCode { get; set; }

        /// <summary>
        ///     An array of payment capabilities supported by the merchant. The array must include 3DS.
        /// </summary>
        /// <value>An array of payment capabilities supported by the merchant. The array must include 3DS.</value>
        [DataMember(Name = "merchantCapabilities", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "merchantCapabilities", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("merchantCapabilities")]
        public List<MessagesApiMessageApplePayPaymentConfigurationMerchantCapability> MerchantCapabilities { get; set; }

        /// <summary>
        ///     An array of payment networks supported by the merchant. The array must include one or more of the following values:
        ///     AMEX, DISCOVER, MASTERCARD, PRIVATE_LABEL or VISA.
        /// </summary>
        /// <value>
        ///     An array of payment networks supported by the merchant. The array must include one or more of the following
        ///     values: AMEX, DISCOVER, MASTERCARD, PRIVATE_LABEL or VISA.
        /// </value>
        [DataMember(Name = "supportedNetworks", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "supportedNetworks", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("supportedNetworks")]
        public List<MessagesApiMessageApplePayPaymentConfigurationNetwork> SupportedNetworks { get; set; }

        /// <summary>
        ///     The list of the customer&#39;s required billing information needed to process the transaction.
        /// </summary>
        /// <value>The list of the customer&#39;s required billing information needed to process the transaction.</value>
        [DataMember(Name = "requiredBillingFields", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "requiredBillingFields", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("requiredBillingFields")]
        public List<MessagesApiMessageApplePayPaymentConfigurationContactField> RequiredBillingFields { get; set; }

        /// <summary>
        ///     The list of shipping or contact information required from the customer to fulfill the order.
        /// </summary>
        /// <value>The list of shipping or contact information required from the customer to fulfill the order.</value>
        [DataMember(Name = "requiredShippingFields", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "requiredShippingFields", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("requiredShippingFields")]
        public List<MessagesApiMessageApplePayPaymentConfigurationContactField> RequiredShippingFields { get; set; }

        /// <summary>
        ///     Called by Apple Pay when the user changes the payment method.
        /// </summary>
        /// <value>Called by Apple Pay when the user changes the payment method.</value>
        [DataMember(Name = "paymentMethodUpdateUrl", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "paymentMethodUpdateUrl", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("paymentMethodUpdateUrl")]
        public string PaymentMethodUpdateUrl { get; set; }

        /// <summary>
        ///     Called by Apple Pay when the user changes their shipping address information.
        /// </summary>
        /// <value>Called by Apple Pay when the user changes their shipping address information.</value>
        [DataMember(Name = "shippingContactUpdateUrl", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "shippingContactUpdateUrl", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("shippingContactUpdateUrl")]
        public string ShippingContactUpdateUrl { get; set; }

        /// <summary>
        ///     Called by Apple Pay when the user changes the shipping method.
        /// </summary>
        /// <value>Called by Apple Pay when the user changes the shipping method.</value>
        [DataMember(Name = "shippingMethodUpdateUrl", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "shippingMethodUpdateUrl", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("shippingMethodUpdateUrl")]
        public string ShippingMethodUpdateUrl { get; set; }

        /// <summary>
        ///     Called by Apple Pay after completing the order provides you with an opportunity to update the order information in
        ///     your system.
        /// </summary>
        /// <value>
        ///     Called by Apple Pay after completing the order provides you with an opportunity to update the order information
        ///     in your system.
        /// </value>
        [DataMember(Name = "orderTrackingUrl", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "orderTrackingUrl", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("orderTrackingUrl")]
        public string OrderTrackingUrl { get; set; }

        /// <summary>
        ///     A URL that opens in a web browser so the user can complete the purchase if their device is unable to make payments
        ///     using Apple Pay.
        /// </summary>
        /// <value>
        ///     A URL that opens in a web browser so the user can complete the purchase if their device is unable to make
        ///     payments using Apple Pay.
        /// </value>
        [DataMember(Name = "fallbackUrl", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "fallbackUrl", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("fallbackUrl")]
        public string FallbackUrl { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiMessageApplePayPaymentConfiguration instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiMessageApplePayPaymentConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiMessageApplePayPaymentConfiguration input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                   (
                       MerchantDomain == input.MerchantDomain ||
                       (MerchantDomain != null &&
                        MerchantDomain.Equals(input.MerchantDomain))
                   ) && base.Equals(input) &&
                   (
                       MerchantDisplayName == input.MerchantDisplayName ||
                       (MerchantDisplayName != null &&
                        MerchantDisplayName.Equals(input.MerchantDisplayName))
                   ) && base.Equals(input) &&
                   (
                       MerchantPaymentGatewayUrl == input.MerchantPaymentGatewayUrl ||
                       (MerchantPaymentGatewayUrl != null &&
                        MerchantPaymentGatewayUrl.Equals(input.MerchantPaymentGatewayUrl))
                   ) && base.Equals(input) &&
                   (
                       MerchantCountryCode == input.MerchantCountryCode ||
                       (MerchantCountryCode != null &&
                        MerchantCountryCode.Equals(input.MerchantCountryCode))
                   ) && base.Equals(input) &&
                   (
                       CurrencyCode == input.CurrencyCode ||
                       (CurrencyCode != null &&
                        CurrencyCode.Equals(input.CurrencyCode))
                   ) && base.Equals(input) &&
                   (
                       MerchantCapabilities == input.MerchantCapabilities ||
                       (MerchantCapabilities != null &&
                        input.MerchantCapabilities != null &&
                        MerchantCapabilities.SequenceEqual(input.MerchantCapabilities))
                   ) && base.Equals(input) &&
                   (
                       SupportedNetworks == input.SupportedNetworks ||
                       (SupportedNetworks != null &&
                        input.SupportedNetworks != null &&
                        SupportedNetworks.SequenceEqual(input.SupportedNetworks))
                   ) && base.Equals(input) &&
                   (
                       RequiredBillingFields == input.RequiredBillingFields ||
                       (RequiredBillingFields != null &&
                        input.RequiredBillingFields != null &&
                        RequiredBillingFields.SequenceEqual(input.RequiredBillingFields))
                   ) && base.Equals(input) &&
                   (
                       RequiredShippingFields == input.RequiredShippingFields ||
                       (RequiredShippingFields != null &&
                        input.RequiredShippingFields != null &&
                        RequiredShippingFields.SequenceEqual(input.RequiredShippingFields))
                   ) && base.Equals(input) &&
                   (
                       PaymentMethodUpdateUrl == input.PaymentMethodUpdateUrl ||
                       (PaymentMethodUpdateUrl != null &&
                        PaymentMethodUpdateUrl.Equals(input.PaymentMethodUpdateUrl))
                   ) && base.Equals(input) &&
                   (
                       ShippingContactUpdateUrl == input.ShippingContactUpdateUrl ||
                       (ShippingContactUpdateUrl != null &&
                        ShippingContactUpdateUrl.Equals(input.ShippingContactUpdateUrl))
                   ) && base.Equals(input) &&
                   (
                       ShippingMethodUpdateUrl == input.ShippingMethodUpdateUrl ||
                       (ShippingMethodUpdateUrl != null &&
                        ShippingMethodUpdateUrl.Equals(input.ShippingMethodUpdateUrl))
                   ) && base.Equals(input) &&
                   (
                       OrderTrackingUrl == input.OrderTrackingUrl ||
                       (OrderTrackingUrl != null &&
                        OrderTrackingUrl.Equals(input.OrderTrackingUrl))
                   ) && base.Equals(input) &&
                   (
                       FallbackUrl == input.FallbackUrl ||
                       (FallbackUrl != null &&
                        FallbackUrl.Equals(input.FallbackUrl))
                   );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiMessageApplePayPaymentConfiguration {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  MerchantDomain: ").Append(MerchantDomain).Append("\n");
            sb.Append("  MerchantDisplayName: ").Append(MerchantDisplayName).Append("\n");
            sb.Append("  MerchantPaymentGatewayUrl: ").Append(MerchantPaymentGatewayUrl).Append("\n");
            sb.Append("  MerchantCountryCode: ").Append(MerchantCountryCode).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  MerchantCapabilities: ").Append(MerchantCapabilities).Append("\n");
            sb.Append("  SupportedNetworks: ").Append(SupportedNetworks).Append("\n");
            sb.Append("  RequiredBillingFields: ").Append(RequiredBillingFields).Append("\n");
            sb.Append("  RequiredShippingFields: ").Append(RequiredShippingFields).Append("\n");
            sb.Append("  PaymentMethodUpdateUrl: ").Append(PaymentMethodUpdateUrl).Append("\n");
            sb.Append("  ShippingContactUpdateUrl: ").Append(ShippingContactUpdateUrl).Append("\n");
            sb.Append("  ShippingMethodUpdateUrl: ").Append(ShippingMethodUpdateUrl).Append("\n");
            sb.Append("  OrderTrackingUrl: ").Append(OrderTrackingUrl).Append("\n");
            sb.Append("  FallbackUrl: ").Append(FallbackUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiMessageApplePayPaymentConfiguration);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();
                if (MerchantDomain != null)
                    hashCode = hashCode * 59 + MerchantDomain.GetHashCode();
                if (MerchantDisplayName != null)
                    hashCode = hashCode * 59 + MerchantDisplayName.GetHashCode();
                if (MerchantPaymentGatewayUrl != null)
                    hashCode = hashCode * 59 + MerchantPaymentGatewayUrl.GetHashCode();
                if (MerchantCountryCode != null)
                    hashCode = hashCode * 59 + MerchantCountryCode.GetHashCode();
                if (CurrencyCode != null)
                    hashCode = hashCode * 59 + CurrencyCode.GetHashCode();
                if (MerchantCapabilities != null)
                    hashCode = hashCode * 59 + MerchantCapabilities.GetHashCode();
                if (SupportedNetworks != null)
                    hashCode = hashCode * 59 + SupportedNetworks.GetHashCode();
                if (RequiredBillingFields != null)
                    hashCode = hashCode * 59 + RequiredBillingFields.GetHashCode();
                if (RequiredShippingFields != null)
                    hashCode = hashCode * 59 + RequiredShippingFields.GetHashCode();
                if (PaymentMethodUpdateUrl != null)
                    hashCode = hashCode * 59 + PaymentMethodUpdateUrl.GetHashCode();
                if (ShippingContactUpdateUrl != null)
                    hashCode = hashCode * 59 + ShippingContactUpdateUrl.GetHashCode();
                if (ShippingMethodUpdateUrl != null)
                    hashCode = hashCode * 59 + ShippingMethodUpdateUrl.GetHashCode();
                if (OrderTrackingUrl != null)
                    hashCode = hashCode * 59 + OrderTrackingUrl.GetHashCode();
                if (FallbackUrl != null)
                    hashCode = hashCode * 59 + FallbackUrl.GetHashCode();
                return hashCode;
            }
        }
    }
}