/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System.Runtime.Serialization;
using Newtonsoft.Json.Converters;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Defines MessagesApiTemplateBodyType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.Text.Json.Serialization.JsonConverter(typeof(JsonStringEnumMemberConverter<MessagesApiTemplateBodyType>))]
    public enum MessagesApiTemplateBodyType
    {
        /// <summary>
        ///     Enum Text for value: TEXT
        /// </summary>
        [EnumMember(Value = "TEXT")] Text = 1,

        /// <summary>
        ///     Enum Carousel for value: CAROUSEL
        /// </summary>
        [EnumMember(Value = "CAROUSEL")] Carousel = 2
    }
}