/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Message ordering options.
    /// </summary>
    [DataContract(Name = "MessagesApiMessageOrderingOptions")]
    [JsonObject]
    public class MessagesApiMessageOrderingOptions : IEquatable<MessagesApiMessageOrderingOptions>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageOrderingOptions" /> class.
        /// </summary>
        /// <param name="respectOrder">
        ///     If set to &#x60;true&#x60;, messages will be sent in the same order as they are provided in
        ///     the request. (default to true).
        /// </param>
        /// <param name="stopOnFailure">
        ///     It can be used in combination with &#x60;respectOrder&#x60; to stop sending messages when
        ///     first message from request fails. (default to true).
        /// </param>
        public MessagesApiMessageOrderingOptions(bool respectOrder = true, bool stopOnFailure = true)
        {
            RespectOrder = respectOrder;
            StopOnFailure = stopOnFailure;
        }

        /// <summary>
        ///     If set to &#x60;true&#x60;, messages will be sent in the same order as they are provided in the request.
        /// </summary>
        /// <value>If set to &#x60;true&#x60;, messages will be sent in the same order as they are provided in the request.</value>
        [DataMember(Name = "respectOrder", EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "respectOrder", DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("respectOrder")]
        public bool RespectOrder { get; set; }

        /// <summary>
        ///     It can be used in combination with &#x60;respectOrder&#x60; to stop sending messages when first message from
        ///     request fails.
        /// </summary>
        /// <value>
        ///     It can be used in combination with &#x60;respectOrder&#x60; to stop sending messages when first message from
        ///     request fails.
        /// </value>
        [DataMember(Name = "stopOnFailure", EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "stopOnFailure", DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("stopOnFailure")]
        public bool StopOnFailure { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiMessageOrderingOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiMessageOrderingOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiMessageOrderingOptions input)
        {
            if (input == null)
                return false;

            return
                (
                    RespectOrder == input.RespectOrder ||
                    RespectOrder.Equals(input.RespectOrder)
                ) &&
                (
                    StopOnFailure == input.StopOnFailure ||
                    StopOnFailure.Equals(input.StopOnFailure)
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiMessageOrderingOptions {\n");
            sb.Append("  RespectOrder: ").Append(RespectOrder).Append("\n");
            sb.Append("  StopOnFailure: ").Append(StopOnFailure).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiMessageOrderingOptions);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                hashCode = hashCode * 59 + RespectOrder.GetHashCode();
                hashCode = hashCode * 59 + StopOnFailure.GetHashCode();
                return hashCode;
            }
        }
    }
}