/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     MessagesApiMessageUpiPayuPaymentConfiguration
    /// </summary>
    [DataContract(Name = "MessagesApiMessageUpiPayuPaymentConfiguration")]
    [JsonObject]
    public class MessagesApiMessageUpiPayuPaymentConfiguration : MessagesApiMessagePaymentConfiguration,
        IEquatable<MessagesApiMessageUpiPayuPaymentConfiguration>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageUpiPayuPaymentConfiguration" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesApiMessageUpiPayuPaymentConfiguration()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageUpiPayuPaymentConfiguration" /> class.
        /// </summary>
        /// <param name="id">Unique identifier of the payment..</param>
        /// <param name="name">Name of the WhatsApp payment configuration to be used for this order..</param>
        /// <param name="productDescription">Brief description of products in this order..</param>
        /// <param name="customerFirstName">Customer&#39;s first name..</param>
        /// <param name="customerLastName">Customer&#39;s last name..</param>
        /// <param name="customerEmail">Customer&#39;s email..</param>
        /// <param name="callbackData">List of custom parameters corresponding to the transaction..</param>
        /// <param name="type">type (required) (default to MessagesApiMessagePaymentConfigurationType.UpiPayu).</param>
        public MessagesApiMessageUpiPayuPaymentConfiguration(string id = default, string name = default,
            string productDescription = default, string customerFirstName = default, string customerLastName = default,
            string customerEmail = default, List<string> callbackData = default,
            MessagesApiMessagePaymentConfigurationType type =
                MessagesApiMessagePaymentConfigurationType.UpiPayu) : base(type)
        {
            Id = id;
            Name = name;
            ProductDescription = productDescription;
            CustomerFirstName = customerFirstName;
            CustomerLastName = customerLastName;
            CustomerEmail = customerEmail;
            CallbackData = callbackData;
        }

        /// <summary>
        ///     Unique identifier of the payment.
        /// </summary>
        /// <value>Unique identifier of the payment.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "id", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        ///     Name of the WhatsApp payment configuration to be used for this order.
        /// </summary>
        /// <value>Name of the WhatsApp payment configuration to be used for this order.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "name", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        ///     Brief description of products in this order.
        /// </summary>
        /// <value>Brief description of products in this order.</value>
        [DataMember(Name = "productDescription", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "productDescription", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("productDescription")]
        public string ProductDescription { get; set; }

        /// <summary>
        ///     Customer&#39;s first name.
        /// </summary>
        /// <value>Customer&#39;s first name.</value>
        [DataMember(Name = "customerFirstName", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "customerFirstName", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("customerFirstName")]
        public string CustomerFirstName { get; set; }

        /// <summary>
        ///     Customer&#39;s last name.
        /// </summary>
        /// <value>Customer&#39;s last name.</value>
        [DataMember(Name = "customerLastName", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "customerLastName", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("customerLastName")]
        public string CustomerLastName { get; set; }

        /// <summary>
        ///     Customer&#39;s email.
        /// </summary>
        /// <value>Customer&#39;s email.</value>
        [DataMember(Name = "customerEmail", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "customerEmail", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("customerEmail")]
        public string CustomerEmail { get; set; }

        /// <summary>
        ///     List of custom parameters corresponding to the transaction.
        /// </summary>
        /// <value>List of custom parameters corresponding to the transaction.</value>
        [DataMember(Name = "callbackData", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "callbackData", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("callbackData")]
        public List<string> CallbackData { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiMessageUpiPayuPaymentConfiguration instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiMessageUpiPayuPaymentConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiMessageUpiPayuPaymentConfiguration input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                   (
                       Id == input.Id ||
                       (Id != null &&
                        Id.Equals(input.Id))
                   ) && base.Equals(input) &&
                   (
                       Name == input.Name ||
                       (Name != null &&
                        Name.Equals(input.Name))
                   ) && base.Equals(input) &&
                   (
                       ProductDescription == input.ProductDescription ||
                       (ProductDescription != null &&
                        ProductDescription.Equals(input.ProductDescription))
                   ) && base.Equals(input) &&
                   (
                       CustomerFirstName == input.CustomerFirstName ||
                       (CustomerFirstName != null &&
                        CustomerFirstName.Equals(input.CustomerFirstName))
                   ) && base.Equals(input) &&
                   (
                       CustomerLastName == input.CustomerLastName ||
                       (CustomerLastName != null &&
                        CustomerLastName.Equals(input.CustomerLastName))
                   ) && base.Equals(input) &&
                   (
                       CustomerEmail == input.CustomerEmail ||
                       (CustomerEmail != null &&
                        CustomerEmail.Equals(input.CustomerEmail))
                   ) && base.Equals(input) &&
                   (
                       CallbackData == input.CallbackData ||
                       (CallbackData != null &&
                        input.CallbackData != null &&
                        CallbackData.SequenceEqual(input.CallbackData))
                   );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiMessageUpiPayuPaymentConfiguration {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ProductDescription: ").Append(ProductDescription).Append("\n");
            sb.Append("  CustomerFirstName: ").Append(CustomerFirstName).Append("\n");
            sb.Append("  CustomerLastName: ").Append(CustomerLastName).Append("\n");
            sb.Append("  CustomerEmail: ").Append(CustomerEmail).Append("\n");
            sb.Append("  CallbackData: ").Append(CallbackData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiMessageUpiPayuPaymentConfiguration);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (ProductDescription != null)
                    hashCode = hashCode * 59 + ProductDescription.GetHashCode();
                if (CustomerFirstName != null)
                    hashCode = hashCode * 59 + CustomerFirstName.GetHashCode();
                if (CustomerLastName != null)
                    hashCode = hashCode * 59 + CustomerLastName.GetHashCode();
                if (CustomerEmail != null)
                    hashCode = hashCode * 59 + CustomerEmail.GetHashCode();
                if (CallbackData != null)
                    hashCode = hashCode * 59 + CallbackData.GetHashCode();
                return hashCode;
            }
        }
    }
}