/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using JsonSubTypes;
using Newtonsoft.Json;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Incoming messages
    /// </summary>
    [DataContract(Name = "MessagesApiInboundEvent")]
    [JsonObject]
    [JsonConverter(typeof(JsonSubtypes), "Event")]
    [JsonSubtypes.KnownSubType(typeof(MessagesApiWebhookEvent), "MO")]
    [JsonSubtypes.KnownSubType(typeof(MessagesApiInboundTypingStartedEvent), "TYPING_STARTED")]
    [JsonSubtypes.KnownSubType(typeof(MessagesApiInboundTypingStoppedEvent), "TYPING_STOPPED")]
    public partial class MessagesApiInboundEvent : IEquatable<MessagesApiInboundEvent>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiInboundEvent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesApiInboundEvent()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiInboundEvent" /> class.
        /// </summary>
        /// <param name="event">@event (required).</param>
        public MessagesApiInboundEvent(MessagesApiInboundEventType @event = default)
        {
            Event = @event;
        }

        /// <summary>
        ///     Gets or Sets Event
        /// </summary>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "event", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("event")]
        public MessagesApiInboundEventType Event { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiInboundEvent instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiInboundEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiInboundEvent input)
        {
            if (input == null)
                return false;

            return
                Event == input.Event ||
                Event.Equals(input.Event);
        }


        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiInboundEvent {\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiInboundEvent);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                hashCode = hashCode * 59 + Event.GetHashCode();
                return hashCode;
            }
        }
    }
}