/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     List of user responses.
    /// </summary>
    [DataContract(Name = "MessagesApiWebhookEventFormSelection")]
    [JsonObject]
    public class MessagesApiWebhookEventFormSelection : IEquatable<MessagesApiWebhookEventFormSelection>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiWebhookEventFormSelection" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesApiWebhookEventFormSelection()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiWebhookEventFormSelection" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="pageIdentifier">Identifier of the form page where the selection was made. (required).</param>
        /// <param name="text">Text of selection. (required).</param>
        /// <param name="items">List of selected items or values provided by the user for this form selection. (required).</param>
        public MessagesApiWebhookEventFormSelection(MessagesApiWebhookEventFormSelectionType type = default,
            string pageIdentifier = default, string text = default,
            List<MessagesApiWebhookEventFormItem> items = default)
        {
            Type = type;
            // to ensure "pageIdentifier" is required (not null)
            PageIdentifier = pageIdentifier ?? throw new ArgumentNullException("pageIdentifier");
            // to ensure "text" is required (not null)
            Text = text ?? throw new ArgumentNullException("text");
            // to ensure "items" is required (not null)
            Items = items ?? throw new ArgumentNullException("items");
        }

        /// <summary>
        ///     Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "type", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("type")]
        public MessagesApiWebhookEventFormSelectionType Type { get; set; }

        /// <summary>
        ///     Identifier of the form page where the selection was made.
        /// </summary>
        /// <value>Identifier of the form page where the selection was made.</value>
        [DataMember(Name = "pageIdentifier", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "pageIdentifier", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("pageIdentifier")]
        public string PageIdentifier { get; set; }

        /// <summary>
        ///     Text of selection.
        /// </summary>
        /// <value>Text of selection.</value>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "text", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        ///     List of selected items or values provided by the user for this form selection.
        /// </summary>
        /// <value>List of selected items or values provided by the user for this form selection.</value>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "items", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("items")]
        public List<MessagesApiWebhookEventFormItem> Items { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiWebhookEventFormSelection instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiWebhookEventFormSelection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiWebhookEventFormSelection input)
        {
            if (input == null)
                return false;

            return
                (
                    Type == input.Type ||
                    Type.Equals(input.Type)
                ) &&
                (
                    PageIdentifier == input.PageIdentifier ||
                    (PageIdentifier != null &&
                     PageIdentifier.Equals(input.PageIdentifier))
                ) &&
                (
                    Text == input.Text ||
                    (Text != null &&
                     Text.Equals(input.Text))
                ) &&
                (
                    Items == input.Items ||
                    (Items != null &&
                     input.Items != null &&
                     Items.SequenceEqual(input.Items))
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiWebhookEventFormSelection {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  PageIdentifier: ").Append(PageIdentifier).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiWebhookEventFormSelection);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                hashCode = hashCode * 59 + Type.GetHashCode();
                if (PageIdentifier != null)
                    hashCode = hashCode * 59 + PageIdentifier.GetHashCode();
                if (Text != null)
                    hashCode = hashCode * 59 + Text.GetHashCode();
                if (Items != null)
                    hashCode = hashCode * 59 + Items.GetHashCode();
                return hashCode;
            }
        }
    }
}