/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     MessagesApiMessageRichLinkBody
    /// </summary>
    [DataContract(Name = "MessagesApiMessageRichLinkBody")]
    [JsonObject]
    public class MessagesApiMessageRichLinkBody : MessagesApiMessageBody, IEquatable<MessagesApiMessageRichLinkBody>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageRichLinkBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesApiMessageRichLinkBody()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageRichLinkBody" /> class.
        /// </summary>
        /// <param name="redirectUrl">URL to be redirected to. (required).</param>
        /// <param name="text">Text to be sent. (required).</param>
        /// <param name="url">
        ///     URL of the rich link. It can be image or video. When you provide it with &#x60;isVideo&#x3D;true
        ///     &#x60; then it will be mapped as a video, otherwise - as an image. (required).
        /// </param>
        /// <param name="isVideo">Indicates if provided &#x60;url&#x60; is a video. (default to false).</param>
        /// <param name="thumbnailUrl">
        ///     URL of the thumbnail image. If you add this, then we use as thumbnail image for video you
        ///     provided in &#x60;url&#x60;. Applicable only when &#x60;isVideo&#x3D;true&#x60;..
        /// </param>
        /// <param name="buttonText">Button label text..</param>
        /// <param name="cardOptions">cardOptions.</param>
        /// <param name="type">type (required) (default to MessagesApiMessageBodyType.RichLink).</param>
        public MessagesApiMessageRichLinkBody(string redirectUrl = default, string text = default, string url = default,
            bool isVideo = false, string thumbnailUrl = default, string buttonText = default,
            MessagesApiMessageCardOptions cardOptions = default,
            MessagesApiMessageBodyType type = MessagesApiMessageBodyType.RichLink) : base(type)
        {
            // to ensure "redirectUrl" is required (not null)
            RedirectUrl = redirectUrl ?? throw new ArgumentNullException("redirectUrl");
            // to ensure "text" is required (not null)
            Text = text ?? throw new ArgumentNullException("text");
            // to ensure "url" is required (not null)
            Url = url ?? throw new ArgumentNullException("url");
            IsVideo = isVideo;
            ThumbnailUrl = thumbnailUrl;
            ButtonText = buttonText;
            CardOptions = cardOptions;
        }

        /// <summary>
        ///     URL to be redirected to.
        /// </summary>
        /// <value>URL to be redirected to.</value>
        [DataMember(Name = "redirectUrl", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "redirectUrl", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("redirectUrl")]
        public string RedirectUrl { get; set; }

        /// <summary>
        ///     Text to be sent.
        /// </summary>
        /// <value>Text to be sent.</value>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "text", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        ///     URL of the rich link. It can be image or video. When you provide it with &#x60;isVideo&#x3D;true&#x60; then it will
        ///     be mapped as a video, otherwise - as an image.
        /// </summary>
        /// <value>
        ///     URL of the rich link. It can be image or video. When you provide it with &#x60;isVideo&#x3D;true&#x60; then it
        ///     will be mapped as a video, otherwise - as an image.
        /// </value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "url", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        ///     Indicates if provided &#x60;url&#x60; is a video.
        /// </summary>
        /// <value>Indicates if provided &#x60;url&#x60; is a video.</value>
        [DataMember(Name = "isVideo", EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "isVideo", DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("isVideo")]
        public bool IsVideo { get; set; }

        /// <summary>
        ///     URL of the thumbnail image. If you add this, then we use as thumbnail image for video you provided in &#x60;url
        ///     &#x60;. Applicable only when &#x60;isVideo&#x3D;true&#x60;.
        /// </summary>
        /// <value>
        ///     URL of the thumbnail image. If you add this, then we use as thumbnail image for video you provided in &#x60;url
        ///     &#x60;. Applicable only when &#x60;isVideo&#x3D;true&#x60;.
        /// </value>
        [DataMember(Name = "thumbnailUrl", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "thumbnailUrl", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("thumbnailUrl")]
        public string ThumbnailUrl { get; set; }

        /// <summary>
        ///     Button label text.
        /// </summary>
        /// <value>Button label text.</value>
        [DataMember(Name = "buttonText", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "buttonText", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("buttonText")]
        public string ButtonText { get; set; }

        /// <summary>
        ///     Gets or Sets CardOptions
        /// </summary>
        [DataMember(Name = "cardOptions", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "cardOptions", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("cardOptions")]
        public MessagesApiMessageCardOptions CardOptions { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiMessageRichLinkBody instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiMessageRichLinkBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiMessageRichLinkBody input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                   (
                       RedirectUrl == input.RedirectUrl ||
                       (RedirectUrl != null &&
                        RedirectUrl.Equals(input.RedirectUrl))
                   ) && base.Equals(input) &&
                   (
                       Text == input.Text ||
                       (Text != null &&
                        Text.Equals(input.Text))
                   ) && base.Equals(input) &&
                   (
                       Url == input.Url ||
                       (Url != null &&
                        Url.Equals(input.Url))
                   ) && base.Equals(input) &&
                   (
                       IsVideo == input.IsVideo ||
                       IsVideo.Equals(input.IsVideo)
                   ) && base.Equals(input) &&
                   (
                       ThumbnailUrl == input.ThumbnailUrl ||
                       (ThumbnailUrl != null &&
                        ThumbnailUrl.Equals(input.ThumbnailUrl))
                   ) && base.Equals(input) &&
                   (
                       ButtonText == input.ButtonText ||
                       (ButtonText != null &&
                        ButtonText.Equals(input.ButtonText))
                   ) && base.Equals(input) &&
                   (
                       CardOptions == input.CardOptions ||
                       (CardOptions != null &&
                        CardOptions.Equals(input.CardOptions))
                   );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiMessageRichLinkBody {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  RedirectUrl: ").Append(RedirectUrl).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  IsVideo: ").Append(IsVideo).Append("\n");
            sb.Append("  ThumbnailUrl: ").Append(ThumbnailUrl).Append("\n");
            sb.Append("  ButtonText: ").Append(ButtonText).Append("\n");
            sb.Append("  CardOptions: ").Append(CardOptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiMessageRichLinkBody);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();
                if (RedirectUrl != null)
                    hashCode = hashCode * 59 + RedirectUrl.GetHashCode();
                if (Text != null)
                    hashCode = hashCode * 59 + Text.GetHashCode();
                if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                hashCode = hashCode * 59 + IsVideo.GetHashCode();
                if (ThumbnailUrl != null)
                    hashCode = hashCode * 59 + ThumbnailUrl.GetHashCode();
                if (ButtonText != null)
                    hashCode = hashCode * 59 + ButtonText.GetHashCode();
                if (CardOptions != null)
                    hashCode = hashCode * 59 + CardOptions.GetHashCode();
                return hashCode;
            }
        }
    }
}