/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System.Runtime.Serialization;
using Newtonsoft.Json.Converters;
using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Messaging channel used for sending an event..
    /// </summary>
    /// <value>Messaging channel used for sending an event.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.Text.Json.Serialization.JsonConverter(
        typeof(JsonStringEnumMemberConverter<MessagesApiOutboundTypingStartedEventChannel>))]
    public enum MessagesApiOutboundTypingStartedEventChannel
    {
        /// <summary>
        ///     Enum AppleMb for value: APPLE_MB
        /// </summary>
        [EnumMember(Value = "APPLE_MB")] AppleMb = 1,

        /// <summary>
        ///     Enum Rcs for value: RCS
        /// </summary>
        [EnumMember(Value = "RCS")] Rcs = 2,

        /// <summary>
        ///     Enum Whatsapp for value: WHATSAPP
        /// </summary>
        [EnumMember(Value = "WHATSAPP")] Whatsapp = 3
    }
}