/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     MessagesApiMessageContactBody
    /// </summary>
    [DataContract(Name = "MessagesApiMessageContactBody")]
    [JsonObject]
    public class MessagesApiMessageContactBody : MessagesApiMessageBody, IEquatable<MessagesApiMessageContactBody>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageContactBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesApiMessageContactBody()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageContactBody" /> class.
        /// </summary>
        /// <param name="name">Name of the contact. (required).</param>
        /// <param name="phoneNumber">Phone number of the contact. (required).</param>
        /// <param name="type">type (required) (default to MessagesApiMessageBodyType.Contact).</param>
        public MessagesApiMessageContactBody(string name = default, string phoneNumber = default,
            MessagesApiMessageBodyType type = MessagesApiMessageBodyType.Contact) : base(type)
        {
            // to ensure "name" is required (not null)
            Name = name ?? throw new ArgumentNullException("name");
            // to ensure "phoneNumber" is required (not null)
            PhoneNumber = phoneNumber ?? throw new ArgumentNullException("phoneNumber");
        }

        /// <summary>
        ///     Name of the contact.
        /// </summary>
        /// <value>Name of the contact.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "name", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        ///     Phone number of the contact.
        /// </summary>
        /// <value>Phone number of the contact.</value>
        [DataMember(Name = "phoneNumber", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "phoneNumber", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("phoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiMessageContactBody instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiMessageContactBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiMessageContactBody input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                   (
                       Name == input.Name ||
                       (Name != null &&
                        Name.Equals(input.Name))
                   ) && base.Equals(input) &&
                   (
                       PhoneNumber == input.PhoneNumber ||
                       (PhoneNumber != null &&
                        PhoneNumber.Equals(input.PhoneNumber))
                   );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiMessageContactBody {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiMessageContactBody);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (PhoneNumber != null)
                    hashCode = hashCode * 59 + PhoneNumber.GetHashCode();
                return hashCode;
            }
        }
    }
}