/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     MessagesApiMessageVideoBody
    /// </summary>
    [DataContract(Name = "MessagesApiMessageVideoBody")]
    [JsonObject]
    public class MessagesApiMessageVideoBody : MessagesApiMessageBody, IEquatable<MessagesApiMessageVideoBody>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageVideoBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesApiMessageVideoBody()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="MessagesApiMessageVideoBody" /> class.
        /// </summary>
        /// <param name="url">URL of the video. (required).</param>
        /// <param name="text">Video caption..</param>
        /// <param name="thumbnailUrl">URL of the thumbnail of the video (required and used only for Viber messages)..</param>
        /// <param name="type">type (required) (default to MessagesApiMessageBodyType.Video).</param>
        public MessagesApiMessageVideoBody(string url = default, string text = default, string thumbnailUrl = default,
            MessagesApiMessageBodyType type = MessagesApiMessageBodyType.Video) : base(type)
        {
            // to ensure "url" is required (not null)
            Url = url ?? throw new ArgumentNullException("url");
            Text = text;
            ThumbnailUrl = thumbnailUrl;
        }

        /// <summary>
        ///     URL of the video.
        /// </summary>
        /// <value>URL of the video.</value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "url", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        ///     Video caption.
        /// </summary>
        /// <value>Video caption.</value>
        [DataMember(Name = "text", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "text", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        ///     URL of the thumbnail of the video (required and used only for Viber messages).
        /// </summary>
        /// <value>URL of the thumbnail of the video (required and used only for Viber messages).</value>
        [DataMember(Name = "thumbnailUrl", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "thumbnailUrl", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("thumbnailUrl")]
        public string ThumbnailUrl { get; set; }

        /// <summary>
        ///     Returns true if MessagesApiMessageVideoBody instances are equal
        /// </summary>
        /// <param name="input">Instance of MessagesApiMessageVideoBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessagesApiMessageVideoBody input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                   (
                       Url == input.Url ||
                       (Url != null &&
                        Url.Equals(input.Url))
                   ) && base.Equals(input) &&
                   (
                       Text == input.Text ||
                       (Text != null &&
                        Text.Equals(input.Text))
                   ) && base.Equals(input) &&
                   (
                       ThumbnailUrl == input.ThumbnailUrl ||
                       (ThumbnailUrl != null &&
                        ThumbnailUrl.Equals(input.ThumbnailUrl))
                   );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessagesApiMessageVideoBody {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  ThumbnailUrl: ").Append(ThumbnailUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MessagesApiMessageVideoBody);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();
                if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                if (Text != null)
                    hashCode = hashCode * 59 + Text.GetHashCode();
                if (ThumbnailUrl != null)
                    hashCode = hashCode * 59 + ThumbnailUrl.GetHashCode();
                return hashCode;
            }
        }
    }
}