/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Object defining display of card media.
    /// </summary>
    [DataContract(Name = "RcsCardMedia")]
    [JsonObject]
    public class RcsCardMedia : IEquatable<RcsCardMedia>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RcsCardMedia" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RcsCardMedia()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="RcsCardMedia" /> class.
        /// </summary>
        /// <param name="file">file (required).</param>
        /// <param name="thumbnail">thumbnail.</param>
        /// <param name="height">height (required).</param>
        public RcsCardMedia(RcsCardResourceSchema file = default, RcsResource thumbnail = default,
            RcsHeight height = default)
        {
            // to ensure "file" is required (not null)
            File = file ?? throw new ArgumentNullException("file");
            Height = height;
            Thumbnail = thumbnail;
        }

        /// <summary>
        ///     Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "height", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("height")]
        public RcsHeight Height { get; set; }

        /// <summary>
        ///     Gets or Sets File
        /// </summary>
        [DataMember(Name = "file", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "file", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("file")]
        public RcsCardResourceSchema File { get; set; }

        /// <summary>
        ///     Gets or Sets Thumbnail
        /// </summary>
        [DataMember(Name = "thumbnail", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "thumbnail", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("thumbnail")]
        public RcsResource Thumbnail { get; set; }

        /// <summary>
        ///     Returns true if RcsCardMedia instances are equal
        /// </summary>
        /// <param name="input">Instance of RcsCardMedia to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RcsCardMedia input)
        {
            if (input == null)
                return false;

            return
                (
                    File == input.File ||
                    (File != null &&
                     File.Equals(input.File))
                ) &&
                (
                    Thumbnail == input.Thumbnail ||
                    (Thumbnail != null &&
                     Thumbnail.Equals(input.Thumbnail))
                ) &&
                (
                    Height == input.Height ||
                    Height.Equals(input.Height)
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RcsCardMedia {\n");
            sb.Append("  File: ").Append(File).Append("\n");
            sb.Append("  Thumbnail: ").Append(Thumbnail).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RcsCardMedia);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (File != null)
                    hashCode = hashCode * 59 + File.GetHashCode();
                if (Thumbnail != null)
                    hashCode = hashCode * 59 + Thumbnail.GetHashCode();
                hashCode = hashCode * 59 + Height.GetHashCode();
                return hashCode;
            }
        }
    }
}