/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     The result of the RCS capability check for the specified phone numbers.
    /// </summary>
    [DataContract(Name = "RcsCapabilityCheckSyncResult")]
    [JsonObject]
    public class RcsCapabilityCheckSyncResult : IEquatable<RcsCapabilityCheckSyncResult>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RcsCapabilityCheckSyncResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RcsCapabilityCheckSyncResult()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="RcsCapabilityCheckSyncResult" /> class.
        /// </summary>
        /// <param name="messageId">
        ///     A unique message ID. This ID is automatically generated and will be included in the API
        ///     response. (required).
        /// </param>
        /// <param name="phoneNumber">The recipient&#39;s phone number that was checked for RCS capability. (required).</param>
        /// <param name="code">code (required).</param>
        public RcsCapabilityCheckSyncResult(string messageId = default, string phoneNumber = default,
            RcsCapabilityCheckResponseCode code = default)
        {
            // to ensure "messageId" is required (not null)
            MessageId = messageId ?? throw new ArgumentNullException("messageId");
            // to ensure "phoneNumber" is required (not null)
            PhoneNumber = phoneNumber ?? throw new ArgumentNullException("phoneNumber");
            Code = code;
        }

        /// <summary>
        ///     Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "code", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("code")]
        public RcsCapabilityCheckResponseCode Code { get; set; }

        /// <summary>
        ///     A unique message ID. This ID is automatically generated and will be included in the API response.
        /// </summary>
        /// <value>A unique message ID. This ID is automatically generated and will be included in the API response.</value>
        [DataMember(Name = "messageId", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "messageId", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("messageId")]
        public string MessageId { get; set; }

        /// <summary>
        ///     The recipient&#39;s phone number that was checked for RCS capability.
        /// </summary>
        /// <value>The recipient&#39;s phone number that was checked for RCS capability.</value>
        [DataMember(Name = "phoneNumber", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "phoneNumber", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("phoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        ///     Returns true if RcsCapabilityCheckSyncResult instances are equal
        /// </summary>
        /// <param name="input">Instance of RcsCapabilityCheckSyncResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RcsCapabilityCheckSyncResult input)
        {
            if (input == null)
                return false;

            return
                (
                    MessageId == input.MessageId ||
                    (MessageId != null &&
                     MessageId.Equals(input.MessageId))
                ) &&
                (
                    PhoneNumber == input.PhoneNumber ||
                    (PhoneNumber != null &&
                     PhoneNumber.Equals(input.PhoneNumber))
                ) &&
                (
                    Code == input.Code ||
                    Code.Equals(input.Code)
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RcsCapabilityCheckSyncResult {\n");
            sb.Append("  MessageId: ").Append(MessageId).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RcsCapabilityCheckSyncResult);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (MessageId != null)
                    hashCode = hashCode * 59 + MessageId.GetHashCode();
                if (PhoneNumber != null)
                    hashCode = hashCode * 59 + PhoneNumber.GetHashCode();
                hashCode = hashCode * 59 + Code.GetHashCode();
                return hashCode;
            }
        }
    }
}