/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Message options.
    /// </summary>
    [DataContract(Name = "RcsFailoverOptions")]
    [JsonObject]
    public class RcsFailoverOptions : IEquatable<RcsFailoverOptions>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RcsFailoverOptions" /> class.
        /// </summary>
        /// <param name="platform">platform.</param>
        /// <param name="validityPeriod">validityPeriod.</param>
        /// <param name="deliveryTimeWindow">deliveryTimeWindow.</param>
        /// <param name="campaignReferenceId">
        ///     ID that allows you to track, analyze, and show an aggregated overview and the
        ///     performance of individual campaigns per sending channel..
        /// </param>
        /// <param name="smsFailover">smsFailover.</param>
        /// <param name="mmsFailover">mmsFailover.</param>
        public RcsFailoverOptions(Platform platform = default, ValidityPeriod validityPeriod = default,
            DeliveryTimeWindow deliveryTimeWindow = default, string campaignReferenceId = default,
            RcsDefaultSmsFailover smsFailover = default, RcsMmsFailover mmsFailover = default)
        {
            Platform = platform;
            ValidityPeriod = validityPeriod;
            DeliveryTimeWindow = deliveryTimeWindow;
            CampaignReferenceId = campaignReferenceId;
            SmsFailover = smsFailover;
            MmsFailover = mmsFailover;
        }

        /// <summary>
        ///     Gets or Sets Platform
        /// </summary>
        [DataMember(Name = "platform", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "platform", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("platform")]
        public Platform Platform { get; set; }

        /// <summary>
        ///     Gets or Sets ValidityPeriod
        /// </summary>
        [DataMember(Name = "validityPeriod", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "validityPeriod", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("validityPeriod")]
        public ValidityPeriod ValidityPeriod { get; set; }

        /// <summary>
        ///     Gets or Sets DeliveryTimeWindow
        /// </summary>
        [DataMember(Name = "deliveryTimeWindow", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "deliveryTimeWindow", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("deliveryTimeWindow")]
        public DeliveryTimeWindow DeliveryTimeWindow { get; set; }

        /// <summary>
        ///     ID that allows you to track, analyze, and show an aggregated overview and the performance of individual campaigns
        ///     per sending channel.
        /// </summary>
        /// <value>
        ///     ID that allows you to track, analyze, and show an aggregated overview and the performance of individual
        ///     campaigns per sending channel.
        /// </value>
        [DataMember(Name = "campaignReferenceId", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "campaignReferenceId", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("campaignReferenceId")]
        public string CampaignReferenceId { get; set; }

        /// <summary>
        ///     Gets or Sets SmsFailover
        /// </summary>
        [DataMember(Name = "smsFailover", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "smsFailover", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("smsFailover")]
        public RcsDefaultSmsFailover SmsFailover { get; set; }

        /// <summary>
        ///     Gets or Sets MmsFailover
        /// </summary>
        [DataMember(Name = "mmsFailover", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "mmsFailover", DefaultValueHandling = DefaultValueHandling.Ignore)]
        [JsonPropertyName("mmsFailover")]
        public RcsMmsFailover MmsFailover { get; set; }

        /// <summary>
        ///     Returns true if RcsFailoverOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of RcsFailoverOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RcsFailoverOptions input)
        {
            if (input == null)
                return false;

            return
                (
                    Platform == input.Platform ||
                    (Platform != null &&
                     Platform.Equals(input.Platform))
                ) &&
                (
                    ValidityPeriod == input.ValidityPeriod ||
                    (ValidityPeriod != null &&
                     ValidityPeriod.Equals(input.ValidityPeriod))
                ) &&
                (
                    DeliveryTimeWindow == input.DeliveryTimeWindow ||
                    (DeliveryTimeWindow != null &&
                     DeliveryTimeWindow.Equals(input.DeliveryTimeWindow))
                ) &&
                (
                    CampaignReferenceId == input.CampaignReferenceId ||
                    (CampaignReferenceId != null &&
                     CampaignReferenceId.Equals(input.CampaignReferenceId))
                ) &&
                (
                    SmsFailover == input.SmsFailover ||
                    (SmsFailover != null &&
                     SmsFailover.Equals(input.SmsFailover))
                ) &&
                (
                    MmsFailover == input.MmsFailover ||
                    (MmsFailover != null &&
                     MmsFailover.Equals(input.MmsFailover))
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RcsFailoverOptions {\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  ValidityPeriod: ").Append(ValidityPeriod).Append("\n");
            sb.Append("  DeliveryTimeWindow: ").Append(DeliveryTimeWindow).Append("\n");
            sb.Append("  CampaignReferenceId: ").Append(CampaignReferenceId).Append("\n");
            sb.Append("  SmsFailover: ").Append(SmsFailover).Append("\n");
            sb.Append("  MmsFailover: ").Append(MmsFailover).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RcsFailoverOptions);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Platform != null)
                    hashCode = hashCode * 59 + Platform.GetHashCode();
                if (ValidityPeriod != null)
                    hashCode = hashCode * 59 + ValidityPeriod.GetHashCode();
                if (DeliveryTimeWindow != null)
                    hashCode = hashCode * 59 + DeliveryTimeWindow.GetHashCode();
                if (CampaignReferenceId != null)
                    hashCode = hashCode * 59 + CampaignReferenceId.GetHashCode();
                if (SmsFailover != null)
                    hashCode = hashCode * 59 + SmsFailover.GetHashCode();
                if (MmsFailover != null)
                    hashCode = hashCode * 59 + MmsFailover.GetHashCode();
                return hashCode;
            }
        }
    }
}