/*
 * Infobip Client API Libraries OpenAPI Specification
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using JsonConstructorAttribute = Newtonsoft.Json.JsonConstructorAttribute;

namespace Infobip.Api.Client.Model
{
    /// <summary>
    ///     Opens the RCS app&#39;s location chooser so the user can pick a location to send back to the agent.
    /// </summary>
    [DataContract(Name = "RcsRequestLocationSuggestion")]
    [JsonObject]
    public class RcsRequestLocationSuggestion : RcsSuggestion, IEquatable<RcsRequestLocationSuggestion>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RcsRequestLocationSuggestion" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RcsRequestLocationSuggestion()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="RcsRequestLocationSuggestion" /> class.
        /// </summary>
        /// <param name="text">Suggestion text. (required).</param>
        /// <param name="postbackData">Value which is going to be sent as a reply to a suggestion. (required).</param>
        /// <param name="type">type (required) (default to RcsSuggestionType.RequestLocation).</param>
        public RcsRequestLocationSuggestion(string text = default, string postbackData = default,
            RcsSuggestionType type = RcsSuggestionType.RequestLocation) : base(type)
        {
            // to ensure "text" is required (not null)
            Text = text ?? throw new ArgumentNullException("text");
            // to ensure "postbackData" is required (not null)
            PostbackData = postbackData ?? throw new ArgumentNullException("postbackData");
        }

        /// <summary>
        ///     Suggestion text.
        /// </summary>
        /// <value>Suggestion text.</value>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "text", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        ///     Value which is going to be sent as a reply to a suggestion.
        /// </summary>
        /// <value>Value which is going to be sent as a reply to a suggestion.</value>
        [DataMember(Name = "postbackData", IsRequired = true, EmitDefaultValue = true)]
        [JsonProperty(PropertyName = "postbackData", Required = Required.DisallowNull,
            DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("postbackData")]
        public string PostbackData { get; set; }

        /// <summary>
        ///     Returns true if RcsRequestLocationSuggestion instances are equal
        /// </summary>
        /// <param name="input">Instance of RcsRequestLocationSuggestion to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RcsRequestLocationSuggestion input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                   (
                       Text == input.Text ||
                       (Text != null &&
                        Text.Equals(input.Text))
                   ) && base.Equals(input) &&
                   (
                       PostbackData == input.PostbackData ||
                       (PostbackData != null &&
                        PostbackData.Equals(input.PostbackData))
                   );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RcsRequestLocationSuggestion {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  PostbackData: ").Append(PostbackData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RcsRequestLocationSuggestion);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = base.GetHashCode();
                if (Text != null)
                    hashCode = hashCode * 59 + Text.GetHashCode();
                if (PostbackData != null)
                    hashCode = hashCode * 59 + PostbackData.GetHashCode();
                return hashCode;
            }
        }
    }
}